# Regression - One Value

In [20]:
import pandas as pd
base = pd.read_csv('../../../datasets/cars.csv', encoding='ISO-8859-1')
base.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

## Preprocessing

In [21]:
# Apagar atributos - axis = 1 (apagar a coluna inteira de todos os registros)
base = base.drop('dateCrawled', axis=1)
base = base.drop('dateCreated', axis=1)
base = base.drop('nrOfPictures', axis=1)
base = base.drop('postalCode', axis=1)
base = base.drop('lastSeen', axis=1)


base.head()

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein

In [22]:
base['name'].value_counts()

Ford_Fiesta                                                          657
BMW_318i                                                             627
Opel_Corsa                                                           622
Volkswagen_Golf_1.4                                                  603
BMW_316i                                                             523
BMW_320i                                                             492
Volkswagen_Polo                                                      475
Renault_Twingo                                                       447
Volkswagen_Golf                                                      428
Volkswagen_Golf_1.6                                                  413
Volkswagen_Polo_1.2                                                  412
BMW_116i                                                             394
Opel_Corsa_1.2_16V                                                   373
Opel_Corsa_B                                                         369
Opel_Astra                                                           366
Peugeot_206                                                          365
Ford_Focus                                                           361
Opel_Corsa_1.0_12V                                                   344
Renault_Twingo_1.2                                                   322
Volkswagen_Passat_Variant_1.9_TDI                                    274
Volkswagen_Golf_1.9_TDI                                              273
Opel_Astra_1.6                                                       260
Audi_A4_Avant_2.0_TDI_DPF                                            254
MINI_Mini_Cooper                                                     245
Ford_Ka                                                              242
Fiat_Punto                                                           242
Audi_A4_Avant_1.9_TDI                                                241
Audi_A4_1.6                                                          238
MINI_Mini_One                                                        233
BMW_520i                                                             226
                                                                    ...
Fiat_126_Maluch                                                        1
Mercedes_Benz_CLK_Cabrio_230_Kompressor_Elegance_plus_Hardtop          1
VW_Golf_4_Bj._2000                                                     1
BMW_325i_Sportpaket                                                    1
golf_gt_guter_zustand                                                  1
Skoda_Octavia_Combi_RS_2.0_TSI                                         1
Seat_xl                                                                1
Audi_Q7_3.0_TDI_DPF_quattro_tiptronic__20_ZOLL_FELGEN                  1
Saab_900_S_Bj._1994_Imolarot_Softturbo_Schiebedach                     1
CORSA_1_3_CDTI_DPF_ERDITON_NAVI_KLIMA_MOTORSCHADEN_KETTE_GERISSEN      1
Audi_A6_Avant_2.7_TDI_DPF_S_Line_/_Navi_/_Leder_/_Xenon                1
Opel_Astra_G_1_6_l_Guter_Zustand_kein_Rost                             1
Audi_A4_2_4__Xenon_Klima_Vollleder_schwarz_Bose                        1
Opel_Meriva_gebraucht___Stadt_/Familienauto                            1
BMW_Cabrio_325_d_e93_Navigation_19_Zoll_M6_Felgen                      1
Audi_100_2.0_E_TÜV_neu__Super_Zustand                                  1
Mitsubishi_Carisma_1_9_Diesel__TÜV_neu__8_Fach_bereift                 1
BMW_520_E39_Tuv_2016/04_Voll_Fahrbereit_Tausch_Moeglic                 1
Twingo_mit_TÜV_Neu_4/2018                                              1
Opel_Astra_1_6_Erste_Hand_53tkm_top_gepflegt                           1
Golf_III_Variant_GT_Yachting                                           1
Omega_2.2_Facelift._Guter_Zustand._Tuev_2/18                           1
VW_PASSAT_3B_1.6L                                                      1
BMW_335xi_N54_Navi_Leder_M_Paket_Performance                           1
Mercedes_Benz_W202_C180_Prins_Gasanlage_~_einiges_neu!                 1
Volkswagen_Golf_4_Highline__gute_Ausstattung__HU_9/17                  1
Fiat_marea_weekend                                                     1
Treuer_Volvo                                                           1
Das_avto_ales_ok_kaini_tuv                                             1
Mercedes_viano_2.2cdi_tuv_2018_03_klima_Automatik                      1
Name: name, Length: 233531, dtype: int64

In [24]:
base = base.drop('name', axis=1)

KeyError: "['name'] not found in axis"

In [26]:
base['seller'].value_counts()

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [27]:
base = base.drop('seller', axis=1)

In [30]:
base['offerType'].value_counts()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [32]:
base = base.drop('offerType', axis=1)

KeyError: "['offerType'] not found in axis"

## Valores Incosistentes

In [37]:
# Buscar registros com determinadas características
i1 = base.loc[base.price <= 10]
i1.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein
40,0,test,NaN,1990,NaN,0,corsa,150000,1,benzin,opel,NaN
60,1,control,suv,1994,manuell,286,NaN,150000,11,NaN,sonstige_autos,NaN
91,1,control,limousine,1995,manuell,113,e_klasse,150000,4,diesel,mercedes_benz,nein
115,0,test,NaN,2017,manuell,0,golf,5000,12,benzin,volkswagen,NaN

In [39]:
base = base[base.price > 10]
base.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein

In [41]:
i2 = base.loc[base.price > 350000]
i2.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000,control,coupe,1980,manuell,277,andere,20000,12,benzin,bmw,nein
10649,420000,control,coupe,2004,manuell,483,911,50000,4,benzin,porsche,nein
14663,11111111,control,coupe,2003,manuell,64,polo,150000,2,benzin,volkswagen,NaN
16889,1000000,control,kombi,1998,NaN,0,mondeo,150000,0,benzin,ford,ja
20143,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein

In [43]:
base = base.loc[base.price < 350000]
base.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein

## Valores Faltantes

In [45]:
base.loc[pd.isnull(base['vehicleType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
22,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
35,350,test,NaN,2016,manuell,75,golf,150000,4,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
48,7750,control,NaN,2017,manuell,80,golf,100000,1,benzin,volkswagen,NaN
51,2000,control,NaN,2017,manuell,90,punto,150000,11,diesel,fiat,ja
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
58,2399,test,NaN,2018,manuell,64,andere,125000,3,NaN,seat,nein
66,10900,test,NaN,2017,manuell,101,astra,50000,3,NaN,opel,nein
72,2300,control,NaN,1997,manuell,150,5er,150000,3,NaN,bmw,nein
78,800,test,NaN,2000,manuell,90,golf,150000,2,diesel,volkswagen,NaN
81,150,control,NaN,2016,manuell,75,astra,150000,3,benzin,opel,ja
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
111,900,test,NaN,1995,manuell,90,civic,150000,3,benzin,honda,NaN
130,8000,control,NaN,2009,manuell,0,golf,100000,10,benzin,volkswagen,nein
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
150,150,control,NaN,1985,NaN,0,100,150000,4,benzin,audi,NaN
152,300,control,NaN,2005,manuell,0,punto,40000,9,NaN,fiat,ja
160,14500,control,NaN,2017,manuell,136,sportage,125000,5,diesel,kia,nein
168,1200,control,NaN,2018,manuell,75,astra,150000,0,NaN,opel,nein
186,3000,control,NaN,2016,automatik,75,fabia,150000,0,benzin,skoda,NaN
202,2800,control,NaN,2018,manuell,75,twingo,125000,12,NaN,renault,nein
206,1999,test,NaN,2016,manuell,110,almera,150000,9,diesel,nissan,NaN
224,2100,test,NaN,2017,manuell,0,zafira,150000,12,diesel,opel,NaN
226,850,control,NaN,1985,manuell,54,caddy,150000,0,diesel,volkswagen,NaN
231,900,test,NaN,2017,manuell,60,corsa,150000,0,benzin,opel,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371146,10980,test,NaN,2018,manuell,75,NaN,20000,1,NaN,volkswagen,nein
371150,1000,control,NaN,2017,manuell,54,NaN,125000,2,NaN,hyundai,nein
371189,350,test,NaN,2000,manuell,50,ibiza,150000,5,NaN,seat,nein
371197,2950,test,NaN,2016,manuell,0,picanto,80000,7,benzin,kia,nein
371210,3700,control,NaN,2016,manuell,90,golf,150000,4,diesel,volkswagen,NaN
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371242,250,control,NaN,2016,manuell,0,3er,150000,5,benzin,bmw,ja
371243,4900,test,NaN,2017,manuell,69,polo,150000,12,diesel,volkswagen,NaN
371245,600,control,NaN,2016,manuell,170,vectra,150000,0,benzin,opel,ja
371252,395,control,NaN,2016,manuell,60,golf,150000,12,benzin,volkswagen,NaN
371258,3600,test,NaN,2017,manuell,86,transit,150000,5,diesel,ford,NaN
371261,299,test,NaN,2016,manuell,60,astra,150000,4,benzin,opel,ja
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371286,1000,control,NaN,2017,manuell,101,a4,150000,9,NaN,audi,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371316,3000,control,NaN,2016,manuell,0,colt,150000,8,diesel,mitsubishi,nein
371349,1350,test,NaN,2016,manuell,0,clk,150000,8,NaN,mercedes_benz,ja
371354,2140,test,NaN,2018,manuell,80,fiesta,150000,6,NaN,ford,nein
371359,8700,test,NaN,2009,NaN,0,2_reihe,90000,8,benzin,peugeot,NaN
371370,790,test,NaN,1990,manuell,0,andere,150000,1,benzin,renault,NaN
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371407,1250,test,NaN,2018,NaN,0,corsa,150000,0,benzin,opel,NaN
371444,5000,control,NaN,2017,manuell,120,andere,150000,7,NaN,citroen,ja
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371493,3299,test,NaN,2005,automatik,0,outlander,150000,4,benzin,mitsubishi,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [47]:
base['vehicleType'].value_counts()

limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: vehicleType, dtype: int64

In [49]:
base.loc[pd.isnull(base['gearbox'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
32,245,test,limousine,1994,NaN,0,golf,150000,2,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
114,350,test,kleinwagen,1998,NaN,0,corsa,150000,2,benzin,opel,NaN
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
150,150,control,NaN,1985,NaN,0,100,150000,4,benzin,audi,NaN
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
166,1495,control,kombi,2001,NaN,64,NaN,150000,9,diesel,volkswagen,NaN
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
203,3200,control,kombi,2006,NaN,0,a3,150000,11,diesel,audi,nein
214,2250,control,kleinwagen,2001,NaN,41,fortwo,150000,10,diesel,smart,nein
240,3750,control,NaN,2005,NaN,75,golf,150000,0,NaN,volkswagen,NaN
245,130,test,kombi,1998,NaN,0,e_klasse,150000,0,NaN,mercedes_benz,NaN
288,2400,test,cabrio,2001,NaN,115,golf,150000,8,benzin,volkswagen,nein
297,1250,control,NaN,2017,NaN,0,espace,150000,8,benzin,renault,NaN
306,2390,test,NaN,2016,NaN,83,jazz,150000,12,benzin,honda,nein
307,1450,control,NaN,2017,NaN,0,a_klasse,150000,8,benzin,mercedes_benz,NaN
308,1699,control,limousine,1999,NaN,75,astra,150000,12,benzin,opel,NaN
318,200,control,NaN,2009,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
321,350,test,NaN,2017,NaN,0,corsa,150000,0,benzin,opel,NaN
367,1050,test,NaN,2018,NaN,0,golf,150000,0,NaN,volkswagen,NaN
371,6250,test,limousine,2003,NaN,299,a6,150000,3,benzin,audi,NaN
372,10000,control,bus,1976,NaN,0,transporter,5000,0,benzin,volkswagen,NaN
376,49500,test,cabrio,2013,NaN,0,NaN,10000,6,benzin,sonstige_autos,nein
404,3400,control,NaN,2018,NaN,0,astra,150000,8,benzin,opel,nein
406,2350,test,NaN,2006,NaN,0,c1,5000,0,andere,citroen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
370796,550,test,NaN,1990,NaN,0,80,5000,0,NaN,audi,NaN
370800,3200,test,bus,1995,NaN,0,transporter,150000,1,diesel,volkswagen,nein
370988,11000,control,bus,2006,NaN,0,vito,150000,11,diesel,mercedes_benz,nein
371029,7900,test,bus,2009,NaN,140,NaN,125000,7,diesel,sonstige_autos,nein
371050,800,control,NaN,1970,NaN,0,andere,150000,0,NaN,trabant,NaN
371056,999,control,NaN,2018,NaN,0,golf,150000,8,NaN,volkswagen,nein
371059,3500,test,kleinwagen,2005,NaN,0,a_klasse,150000,0,NaN,mercedes_benz,NaN
371068,750,control,kleinwagen,2001,NaN,0,andere,150000,0,benzin,hyundai,NaN
371075,850,test,coupe,2000,NaN,0,astra,150000,11,benzin,opel,NaN
371088,1000,control,NaN,2005,NaN,0,astra,150000,0,NaN,opel,NaN
371099,200,control,NaN,1910,NaN,0,NaN,5000,0,benzin,sonstige_autos,NaN
371142,250,test,cabrio,1997,NaN,0,punto,150000,0,NaN,fiat,NaN
371144,210,test,kleinwagen,1997,NaN,60,polo,150000,0,NaN,volkswagen,NaN
371181,3590,control,coupe,2000,NaN,0,3er,150000,10,NaN,bmw,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371279,250,test,kleinwagen,1994,NaN,75,golf,150000,6,benzin,volkswagen,nein
371299,13500,test,suv,2005,NaN,0,xc_reihe,150000,0,diesel,volvo,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371359,8700,test,NaN,2009,NaN,0,2_reihe,90000,8,benzin,peugeot,NaN
371375,4300,control,kleinwagen,2009,NaN,0,ibiza,150000,3,benzin,seat,nein
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371407,1250,test,NaN,2018,NaN,0,corsa,150000,0,benzin,opel,NaN
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371440,3500,control,kleinwagen,2001,NaN,75,corsa,90000,4,benzin,opel,nein
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [51]:
base['gearbox'].value_counts()

manuell      266547
automatik     75508
Name: gearbox, dtype: int64

In [52]:
base.loc[pd.isnull(base['model'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
166,1495,control,kombi,2001,NaN,64,NaN,150000,9,diesel,volkswagen,NaN
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
199,1200,test,coupe,1990,manuell,45,NaN,150000,0,benzin,volkswagen,NaN
268,450,control,NaN,2016,manuell,0,NaN,150000,3,benzin,mitsubishi,nein
285,1500,control,coupe,1994,manuell,116,NaN,150000,8,NaN,audi,nein
318,200,control,NaN,2009,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
320,1600,test,kombi,1999,manuell,0,NaN,150000,6,benzin,bmw,nein
365,5500,test,kleinwagen,2012,manuell,68,NaN,40000,12,NaN,peugeot,nein
373,300,control,kleinwagen,2001,manuell,0,NaN,150000,5,benzin,peugeot,ja
376,49500,test,cabrio,2013,NaN,0,NaN,10000,6,benzin,sonstige_autos,nein
427,13950,control,andere,2011,manuell,140,NaN,60000,11,diesel,alfa_romeo,nein
446,3950,test,kleinwagen,2004,automatik,5,NaN,70000,5,diesel,sonstige_autos,nein
450,1300,control,NaN,2017,manuell,150,NaN,150000,10,NaN,volkswagen,nein
451,5800,control,bus,2007,manuell,105,NaN,150000,11,diesel,volkswagen,ja
458,1950,control,NaN,2017,manuell,0,NaN,150000,7,benzin,volkswagen,nein
563,2600,control,NaN,2005,NaN,0,NaN,125000,0,NaN,chevrolet,NaN
577,50,test,NaN,1985,NaN,0,NaN,150000,11,NaN,trabant,NaN
612,3800,test,cabrio,2005,manuell,109,NaN,100000,12,benzin,peugeot,NaN
644,1600,test,kleinwagen,2002,manuell,64,NaN,150000,2,benzin,volkswagen,nein
658,7400,test,cabrio,2003,automatik,192,NaN,150000,8,NaN,bmw,nein
672,2200,test,limousine,1995,automatik,299,NaN,150000,5,NaN,audi,ja
677,1900,control,limousine,2000,manuell,125,NaN,150000,5,benzin,mitsubishi,nein
678,15000,test,coupe,1971,NaN,0,NaN,5000,4,NaN,sonstige_autos,nein
690,9900,test,suv,2000,automatik,250,NaN,150000,4,lpg,sonstige_autos,nein
698,5900,control,kombi,2004,manuell,150,NaN,150000,2,diesel,mercedes_benz,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
370819,400,control,kombi,1998,manuell,105,NaN,150000,7,benzin,volvo,NaN
370836,900,control,NaN,2017,manuell,101,NaN,150000,6,NaN,opel,NaN
370890,250,control,kleinwagen,1997,manuell,66,NaN,150000,5,benzin,sonstige_autos,NaN
370903,650,test,NaN,2000,manuell,150,NaN,150000,7,NaN,audi,nein
370952,9800,control,kleinwagen,2013,manuell,90,NaN,50000,4,NaN,renault,NaN
370968,11690,control,kombi,2005,automatik,224,NaN,150000,5,diesel,audi,nein
371001,2800,control,coupe,2003,manuell,163,NaN,150000,7,benzin,citroen,NaN
371004,5000,test,limousine,2006,manuell,175,NaN,125000,12,benzin,sonstige_autos,nein
371029,7900,test,bus,2009,NaN,140,NaN,125000,7,diesel,sonstige_autos,nein
371060,2200,test,suv,1994,manuell,124,NaN,150000,0,benzin,ford,nein
371065,18500,test,limousine,2009,automatik,190,NaN,150000,10,diesel,audi,nein
371099,200,control,NaN,1910,NaN,0,NaN,5000,0,benzin,sonstige_autos,NaN
371102,1599,test,kleinwagen,2002,manuell,75,NaN,150000,0,benzin,ford,NaN
371110,1670,control,NaN,2018,manuell,0,NaN,90000,0,benzin,renault,nein
371121,1500,control,bus,1984,manuell,0,NaN,150000,5,diesel,mercedes_benz,NaN
371146,10980,test,NaN,2018,manuell,75,NaN,20000,1,NaN,volkswagen,nein
371150,1000,control,NaN,2017,manuell,54,NaN,125000,2,NaN,hyundai,nein
371196,42000,control,limousine,2012,automatik,564,NaN,50000,3,benzin,sonstige_autos,nein
371203,6000,test,kleinwagen,2008,manuell,155,NaN,150000,5,benzin,sonstige_autos,nein
371214,30900,control,cabrio,1960,automatik,250,NaN,100000,7,benzin,sonstige_autos,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371220,200,control,kleinwagen,1998,manuell,37,NaN,150000,4,benzin,volkswagen,ja
371223,4300,test,kleinwagen,2008,automatik,0,NaN,150000,3,NaN,honda,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371388,5000,control,limousine,2002,automatik,170,NaN,150000,0,benzin,audi,nein
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [54]:
base['model'].value_counts()

golf                  28989
andere                25560
3er                   19905
polo                  12604
corsa                 12149
astra                 10458
a4                     9972
passat                 9966
c_klasse               8624
5er                    8304
e_klasse               7379
a3                     6498
a6                     5832
focus                  5805
fiesta                 5645
transporter            5371
twingo                 4804
2_reihe                4753
fortwo                 4286
a_klasse               4241
vectra                 4072
1er                    3818
mondeo                 3503
touran                 3492
clio                   3456
3_reihe                3427
punto                  3238
zafira                 2983
megane                 2809
ibiza                  2634
                      ...
mii                      81
crossfire                66
range_rover_evoque       65
gl                       63
nubira                   61
move                     51
lybra                    50
v60                      48
croma                    45
145                      45
delta                    39
amarok                   39
lodgy                    35
terios                   35
9000                     28
charade                  27
b_max                    26
musa                     23
materia                  18
200                      17
kappa                    15
samara                   12
elefantino               11
i3                       10
kalina                    9
serie_2                   8
rangerover                6
serie_3                   3
discovery_sport           1
serie_1                   1
Name: model, Length: 251, dtype: int64

In [56]:
base.loc[pd.isnull(base['fuelType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
13,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
54,4700,control,kombi,2005,manuell,0,signum,150000,0,NaN,opel,nein
58,2399,test,NaN,2018,manuell,64,andere,125000,3,NaN,seat,nein
66,10900,test,NaN,2017,manuell,101,astra,50000,3,NaN,opel,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
72,2300,control,NaN,1997,manuell,150,5er,150000,3,NaN,bmw,nein
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
99,6450,test,bus,2008,manuell,84,transporter,150000,12,NaN,volkswagen,nein
108,300,test,cabrio,1992,manuell,105,escort,150000,0,NaN,ford,ja
123,400,control,limousine,2000,manuell,144,omega,150000,10,NaN,opel,ja
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
147,1500,test,kombi,1996,manuell,126,a4,150000,0,NaN,audi,nein
152,300,control,NaN,2005,manuell,0,punto,40000,9,NaN,fiat,ja
164,1499,test,kleinwagen,2002,manuell,140,a_klasse,150000,10,NaN,mercedes_benz,nein
168,1200,control,NaN,2018,manuell,75,astra,150000,0,NaN,opel,nein
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
202,2800,control,NaN,2018,manuell,75,twingo,125000,12,NaN,renault,nein
221,1000,test,kombi,1999,manuell,165,a6,150000,0,NaN,audi,NaN
233,1600,test,kombi,2000,manuell,90,cordoba,150000,11,NaN,seat,nein
240,3750,control,NaN,2005,NaN,75,golf,150000,0,NaN,volkswagen,NaN
245,130,test,kombi,1998,NaN,0,e_klasse,150000,0,NaN,mercedes_benz,NaN
256,8000,test,limousine,2006,manuell,177,impreza,150000,0,NaN,subaru,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371174,700,test,kleinwagen,1997,manuell,60,polo,150000,0,NaN,volkswagen,NaN
371175,1500,control,kleinwagen,1998,manuell,75,golf,150000,12,NaN,volkswagen,NaN
371177,10500,test,cabrio,1968,manuell,54,andere,20000,4,NaN,renault,nein
371181,3590,control,coupe,2000,NaN,0,3er,150000,10,NaN,bmw,nein
371189,350,test,NaN,2000,manuell,50,ibiza,150000,5,NaN,seat,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371223,4300,test,kleinwagen,2008,automatik,0,NaN,150000,3,NaN,honda,NaN
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371286,1000,control,NaN,2017,manuell,101,a4,150000,9,NaN,audi,NaN
371287,999,test,kombi,1997,manuell,170,5er,150000,6,NaN,bmw,nein
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371323,1999,test,kleinwagen,2002,manuell,75,golf,150000,0,NaN,volkswagen,NaN
371342,5000,control,coupe,1999,automatik,0,3er,150000,0,NaN,bmw,NaN
371349,1350,test,NaN,2016,manuell,0,clk,150000,8,NaN,mercedes_benz,ja
371354,2140,test,NaN,2018,manuell,80,fiesta,150000,6,NaN,ford,nein
371378,240,control,kleinwagen,1995,manuell,75,polo,150000,7,NaN,volkswagen,NaN
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371390,1799,test,kombi,2005,manuell,180,signum,150000,1,NaN,opel,ja
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371419,3000,control,limousine,2001,automatik,150,a4,150000,8,NaN,audi,ja
371444,5000,control,NaN,2017,manuell,120,andere,150000,7,NaN,citroen,ja
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371482,1300,control,kleinwagen,1999,manuell,75,2_reihe,125000,0,NaN,peugeot,NaN
371484,2999,test,kombi,2004,manuell,234,vectra,100000,1,NaN,opel,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371496,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [58]:
base['fuelType'].value_counts()

benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: fuelType, dtype: int64

In [59]:
base.loc[pd.isnull(base['notRepairedDamage'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
12,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
42,12500,test,limousine,2006,automatik,231,5er,150000,11,diesel,bmw,NaN
44,3900,test,kleinwagen,2008,automatik,61,fortwo,80000,6,benzin,smart,NaN
48,7750,control,NaN,2017,manuell,80,golf,100000,1,benzin,volkswagen,NaN
50,14800,control,cabrio,2008,manuell,170,1er,125000,4,benzin,bmw,NaN
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
53,7999,control,limousine,2008,automatik,143,3er,150000,12,diesel,bmw,NaN
61,200,test,coupe,1995,manuell,102,3er,150000,4,benzin,bmw,NaN
69,1280,control,limousine,1992,automatik,109,andere,150000,9,benzin,mercedes_benz,NaN
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
78,800,test,NaN,2000,manuell,90,golf,150000,2,diesel,volkswagen,NaN
87,8000,test,suv,2005,manuell,185,xc_reihe,150000,8,diesel,volvo,NaN
92,2400,test,limousine,2003,manuell,0,a4,150000,9,diesel,audi,NaN
93,1222,control,limousine,1984,automatik,180,andere,150000,3,benzin,opel,NaN
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
103,499,control,limousine,1995,manuell,101,a4,150000,5,benzin,audi,NaN
105,6500,test,limousine,2004,manuell,163,a4,150000,4,diesel,audi,NaN
107,650,test,limousine,1997,automatik,102,3er,150000,8,benzin,bmw,NaN
111,900,test,NaN,1995,manuell,90,civic,150000,3,benzin,honda,NaN
114,350,test,kleinwagen,1998,NaN,0,corsa,150000,2,benzin,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371416,700,test,kombi,1997,manuell,145,galaxy,150000,6,benzin,ford,NaN
371418,4700,test,bus,2004,manuell,101,touran,150000,2,diesel,volkswagen,NaN
371420,399,control,kleinwagen,1992,manuell,45,polo,150000,4,benzin,volkswagen,NaN
371422,1599,control,kombi,2002,manuell,101,astra,150000,9,benzin,opel,NaN
371424,9000,control,kombi,2005,manuell,0,a6,150000,0,diesel,audi,NaN
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371445,2500,control,kleinwagen,2007,manuell,60,andere,125000,3,benzin,hyundai,NaN
371448,480,test,limousine,1996,manuell,136,c_klasse,150000,6,benzin,mercedes_benz,NaN
371450,1500,test,limousine,1991,manuell,94,e_klasse,150000,10,diesel,mercedes_benz,NaN
371452,400,test,kombi,1996,manuell,150,a4,150000,0,benzin,audi,NaN
371454,5800,test,kombi,2003,manuell,168,a6,150000,4,diesel,audi,NaN
371457,5990,control,bus,1984,automatik,0,andere,70000,4,benzin,chevrolet,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371473,400,control,kombi,1991,manuell,0,legacy,150000,0,benzin,subaru,NaN
371475,1500,control,limousine,1999,manuell,75,golf,150000,4,benzin,volkswagen,NaN
371482,1300,control,kleinwagen,1999,manuell,75,2_reihe,125000,0,NaN,peugeot,NaN
371484,2999,test,kombi,2004,manuell,234,vectra,100000,1,NaN,opel,NaN
371485,4200,control,limousine,2001,automatik,193,5er,150000,1,diesel,bmw,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371493,3299,test,NaN,2005,automatik,0,outlander,150000,4,benzin,mitsubishi,NaN
371494,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371498,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371507,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN
371514,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN
371515,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN

In [61]:
base['notRepairedDamage'].value_counts()

nein    259301
ja       34004
Name: notRepairedDamage, dtype: int64

In [63]:
values = {'vehicleType': 'limousine', 'gearbox': 'manuell',
           'model': 'golf', 'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}

In [66]:
# Vamos substituir os valores faltantes pelos mais frequentes. Esta técnica é empregada em atributos do tipo categóricos
base = base.fillna(value=values)
base.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,limousine,1993,manuell,0,golf,150000,0,benzin,volkswagen,nein
1,18300,test,coupe,2011,manuell,190,golf,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,nein
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein

## Label Encoder

In [70]:
data = base.iloc[:, 1:13].values
price_target = base.iloc[:,0].values

In [78]:
from sklearn.preprocessing import LabelEncoder

labelenconder_data = LabelEncoder()
data[:, 0] = labelenconder_data.fit_transform(data[:, 0])
data[:, 1] = labelenconder_data.fit_transform(data[:, 1])
data[:, 3] = labelenconder_data.fit_transform(data[:, 3])
data[:, 5] = labelenconder_data.fit_transform(data[:, 5])
data[:, 8] = labelenconder_data.fit_transform(data[:, 8])
data[:, 9] = labelenconder_data.fit_transform(data[:, 9])
data[:, 10] = labelenconder_data.fit_transform(data[:, 10])

data

array([[1, 6, 1993, ..., 1, 38, 1],
       [1, 3, 2011, ..., 3, 1, 0],
       [1, 7, 2004, ..., 3, 14, 1],
       ...,
       [1, 1, 1996, ..., 3, 38, 1],
       [1, 5, 2002, ..., 3, 38, 1],
       [0, 6, 2013, ..., 1, 2, 1]], dtype=object)

## One Hot Encoder

In [82]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(categorical_features = [0,1,3,5,8,9,10])
data = one_hot_encoder.fit_transform(data).toarray()

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [83]:
data

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.50000000e+05,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.90000000e+02,   1.25000000e+05,   5.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.63000000e+02,   1.25000000e+05,   8.00000000e+00],
       ...,
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.02000000e+02,   1.50000000e+05,   3.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+02,   1.50000000e+05,   6.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   1.00000000e+00, ...,
          3.20000000e+02,   5.00000000e+04,   8.00000000e+00]])

## Train

In [85]:
from keras.models import Sequential
from keras.layers import Dense

In [88]:
regressor = Sequential()
# Para determinar o número de neurônios: (número de atributos previsores + número de classes)/ 2
# Utiliza-se 'relu' para problemas de regressão
regressor.add(Dense(units=158, activation='relu',input_dim=323))
regressor.add(Dense(units=158, activation='relu'))

# Camada de Saída
regressor.add(Dense(units=1, activation='linear'))
regressor.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mean_absolute_error'])

regressor.fit(data, price_target, batch_size = 300, epochs=100)

Epoch 1/100
359291/359291 [==============================] - 4s 12us/step - loss: 3856.2482 - mean_absolute_error: 3856.2482
Epoch 2/100
359291/359291 [==============================] - 4s 11us/step - loss: 3334.3030 - mean_absolute_error: 3334.3030
Epoch 3/100
359291/359291 [==============================] - 5s 13us/step - loss: 3116.7133 - mean_absolute_error: 3116.7133
Epoch 4/100
359291/359291 [==============================] - 5s 15us/step - loss: 2976.0376 - mean_absolute_error: 2976.0376
Epoch 5/100
359291/359291 [==============================] - 7s 18us/step - loss: 2885.5081 - mean_absolute_error: 2885.5081
Epoch 6/100
359291/359291 [==============================] - 9s 26us/step - loss: 2812.2663 - mean_absolute_error: 2812.2663
Epoch 7/100
359291/359291 [==============================] - 8s 22us/step - loss: 2735.4632 - mean_absolute_error: 2735.4632
Epoch 8/100
359291/359291 [==============================] - 9s 25us/step - loss: 2693.1014 - mean_absolute_error: 2693.1014
Epoch 9/100
359291/359291 [==============================] - 7s 20us/step - loss: 2636.8798 - mean_absolute_error: 2636.8798
Epoch 10/100
359291/359291 [==============================] - 7s 21us/step - loss: 2582.6239 - mean_absolute_error: 2582.6239
Epoch 11/100
359291/359291 [==============================] - 6s 16us/step - loss: 2551.8455 - mean_absolute_error: 2551.8455
Epoch 12/100
359291/359291 [==============================] - 6s 17us/step - loss: 2523.4040 - mean_absolute_error: 2523.4040
Epoch 13/100
359291/359291 [==============================] - 6s 17us/step - loss: 2506.0603 - mean_absolute_error: 2506.0603
Epoch 14/100
359291/359291 [==============================] - 6s 18us/step - loss: 2484.6205 - mean_absolute_error: 2484.6205
Epoch 15/100
359291/359291 [==============================] - 6s 17us/step - loss: 2467.4726 - mean_absolute_error: 2467.4726
Epoch 16/100
359291/359291 [==============================] - 6s 18us/step - loss: 2453.6072 - mean_absolute_error: 2453.6072
Epoch 17/100
359291/359291 [==============================] - 6s 17us/step - loss: 2454.3740 - mean_absolute_error: 2454.3740
Epoch 18/100
359291/359291 [==============================] - 6s 16us/step - loss: 2436.0819 - mean_absolute_error: 2436.0819
Epoch 19/100
359291/359291 [==============================] - 6s 17us/step - loss: 2426.5914 - mean_absolute_error: 2426.5914
Epoch 20/100
359291/359291 [==============================] - 6s 16us/step - loss: 2422.7862 - mean_absolute_error: 2422.7862
Epoch 21/100
359291/359291 [==============================] - 6s 17us/step - loss: 2410.1527 - mean_absolute_error: 2410.1527
Epoch 22/100
359291/359291 [==============================] - 6s 17us/step - loss: 2411.2669 - mean_absolute_error: 2411.2669
Epoch 23/100
359291/359291 [==============================] - 6s 17us/step - loss: 2421.0481 - mean_absolute_error: 2421.0481
Epoch 24/100
359291/359291 [==============================] - 6s 17us/step - loss: 2394.0819 - mean_absolute_error: 2394.0819
Epoch 25/100
359291/359291 [==============================] - 6s 17us/step - loss: 2381.7606 - mean_absolute_error: 2381.7606
Epoch 26/100
359291/359291 [==============================] - 6s 17us/step - loss: 2393.0619 - mean_absolute_error: 2393.0619
Epoch 27/100
359291/359291 [==============================] - 6s 18us/step - loss: 2383.2531 - mean_absolute_error: 2383.2531
Epoch 28/100
359291/359291 [==============================] - 6s 16us/step - loss: 2370.9708 - mean_absolute_error: 2370.9708
Epoch 29/100
359291/359291 [==============================] - 7s 18us/step - loss: 2387.9460 - mean_absolute_error: 2387.9460
Epoch 30/100
359291/359291 [==============================] - 6s 16us/step - loss: 2377.4388 - mean_absolute_error: 2377.4388
Epoch 31/100
359291/359291 [==============================] - 6s 18us/step - loss: 2371.6062 - mean_absolute_error: 2371.6062
Epoch 32/100
359291/359291 [==============================] - 6s 15us/step - loss: 2365.6963 - mean_absolute_error: 2365.6963
Epoch 33/100
359291/359291 [==============================] - 7s 19us/step - loss: 2379.0304 - mean_absolute_error: 2379.0304
Epoch 34/100
359291/359291 [==============================] - 6s 17us/step - loss: 2349.0665 - mean_absolute_error: 2349.0665
Epoch 35/100
359291/359291 [==============================] - 7s 18us/step - loss: 2352.0069 - mean_absolute_error: 2352.0069
Epoch 36/100
359291/359291 [==============================] - 5s 15us/step - loss: 2350.1022 - mean_absolute_error: 2350.1022
Epoch 37/100
359291/359291 [==============================] - 7s 19us/step - loss: 2343.4200 - mean_absolute_error: 2343.4200
Epoch 38/100
359291/359291 [==============================] - 6s 15us/step - loss: 2339.7668 - mean_absolute_error: 2339.7668
Epoch 39/100
359291/359291 [==============================] - 7s 19us/step - loss: 2327.7689 - mean_absolute_error: 2327.7689
Epoch 40/100
359291/359291 [==============================] - 6s 16us/step - loss: 2359.6607 - mean_absolute_error: 2359.6607
Epoch 41/100
359291/359291 [==============================] - 7s 18us/step - loss: 2317.2859 - mean_absolute_error: 2317.2859
Epoch 42/100
359291/359291 [==============================] - 6s 17us/step - loss: 2331.4372 - mean_absolute_error: 2331.4372
Epoch 43/100
359291/359291 [==============================] - 10s 28us/step - loss: 2326.0207 - mean_absolute_error: 2326.0207
Epoch 44/100
359291/359291 [==============================] - 9s 26us/step - loss: 2326.2929 - mean_absolute_error: 2326.2929
Epoch 45/100
359291/359291 [==============================] - 11s 32us/step - loss: 2332.5223 - mean_absolute_error: 2332.5223
Epoch 46/100
359291/359291 [==============================] - 10s 27us/step - loss: 2318.3323 - mean_absolute_error: 2318.3323
Epoch 47/100
359291/359291 [==============================] - 11s 30us/step - loss: 2318.6279 - mean_absolute_error: 2318.6279
Epoch 48/100
359291/359291 [==============================] - 11s 30us/step - loss: 2310.7647 - mean_absolute_error: 2310.7647
Epoch 49/100
359291/359291 [==============================] - 11s 30us/step - loss: 2316.8965 - mean_absolute_error: 2316.8965
Epoch 50/100
359291/359291 [==============================] - 11s 32us/step - loss: 2309.4504 - mean_absolute_error: 2309.4504
Epoch 51/100
359291/359291 [==============================] - 10s 28us/step - loss: 2319.9543 - mean_absolute_error: 2319.9543
Epoch 52/100
359291/359291 [==============================] - 11s 30us/step - loss: 2304.1756 - mean_absolute_error: 2304.1756
Epoch 53/100
359291/359291 [==============================] - 12s 33us/step - loss: 2305.6906 - mean_absolute_error: 2305.6906
Epoch 54/100
359291/359291 [==============================] - 16s 43us/step - loss: 2315.3387 - mean_absolute_error: 2315.3387
Epoch 55/100
359291/359291 [==============================] - 9s 24us/step - loss: 2312.6457 - mean_absolute_error: 2312.6457
Epoch 56/100
359291/359291 [==============================] - 8s 21us/step - loss: 2288.7538 - mean_absolute_error: 2288.7538
Epoch 57/100
359291/359291 [==============================] - 8s 21us/step - loss: 2313.3083 - mean_absolute_error: 2313.3083
Epoch 58/100
359291/359291 [==============================] - 6s 18us/step - loss: 2288.8325 - mean_absolute_error: 2288.8325
Epoch 59/100
359291/359291 [==============================] - 8s 23us/step - loss: 2292.0936 - mean_absolute_error: 2292.0936
Epoch 60/100
359291/359291 [==============================] - 8s 22us/step - loss: 2290.0115 - mean_absolute_error: 2290.0115
Epoch 61/100
359291/359291 [==============================] - 8s 23us/step - loss: 2291.0942 - mean_absolute_error: 2291.0942
Epoch 62/100
359291/359291 [==============================] - 6s 17us/step - loss: 2293.2094 - mean_absolute_error: 2293.2094
Epoch 63/100
359291/359291 [==============================] - 7s 20us/step - loss: 2277.6289 - mean_absolute_error: 2277.6289
Epoch 64/100
359291/359291 [==============================] - 8s 21us/step - loss: 2290.2989 - mean_absolute_error: 2290.2989
Epoch 65/100
359291/359291 [==============================] - 8s 23us/step - loss: 2301.1375 - mean_absolute_error: 2301.1375
Epoch 66/100

359291/359291 [==============================] - 8s 24us/step - loss: 2283.0794 - mean_absolute_error: 2283.0794
Epoch 67/100
359291/359291 [==============================] - 10s 28us/step - loss: 2287.8613 - mean_absolute_error: 2287.8613
Epoch 68/100
359291/359291 [==============================] - 10s 29us/step - loss: 2275.0028 - mean_absolute_error: 2275.0028
Epoch 69/100
359291/359291 [==============================] - 9s 24us/step - loss: 2280.3779 - mean_absolute_error: 2280.3779
Epoch 70/100
359291/359291 [==============================] - 10s 27us/step - loss: 2281.0753 - mean_absolute_error: 2281.0753
Epoch 71/100
359291/359291 [==============================] - 6s 17us/step - loss: 2274.1232 - mean_absolute_error: 2274.1232
Epoch 72/100
359291/359291 [==============================] - 11s 31us/step - loss: 2270.1237 - mean_absolute_error: 2270.1237
Epoch 73/100
359291/359291 [==============================] - 6s 18us/step - loss: 2267.9514 - mean_absolute_error: 2267.9514
Epoch 74/100
359291/359291 [==============================] - 10s 27us/step - loss: 2264.5854 - mean_absolute_error: 2264.5854
Epoch 75/100
359291/359291 [==============================] - 9s 26us/step - loss: 2277.0042 - mean_absolute_error: 2277.0042
Epoch 76/100
359291/359291 [==============================] - 12s 33us/step - loss: 2268.8848 - mean_absolute_error: 2268.8848
Epoch 77/100
359291/359291 [==============================] - 10s 28us/step - loss: 2279.9018 - mean_absolute_error: 2279.9018
Epoch 78/100
359291/359291 [==============================] - 11s 30us/step - loss: 2277.9453 - mean_absolute_error: 2277.9453
Epoch 79/100
219300/359291 [=================>............] - ETA: 3s - loss: 2273.9975 - mean_absolute_error: 2273.9975

KeyboardInterrupt:

In [ ]:
predicitions = regressor.predict(data)

## Validação Cruzada

In [89]:
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
import keras

In [90]:
def build_neural_network():
    regressor = Sequential()
    regressor.add(Dense(units=158, activation='relu',input_dim=323))
    regressor.add(Dense(units=158, activation='relu'))
    regressor.add(Dense(units=1, activation='linear'))
    regressor.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mean_absolute_error'])
    
    return regressor

In [96]:
regressor = KerasRegressor(build_fn=build_neural_network, epochs=100, batch_size=300)
results = cross_val_score(estimator=regressor, X=data, y=price_target, cv=10, scoring="neg_mean_absolute_error")
mean = resultados.mean()
std = std.mean()

Epoch 1/100
359291/359291 [==============================] - 5s 14us/step - loss: 3829.3852 - mean_absolute_error: 3829.3852
Epoch 2/100
359291/359291 [==============================] - 6s 16us/step - loss: 3414.2551 - mean_absolute_error: 3414.2551
Epoch 3/100
359291/359291 [==============================] - 6s 17us/step - loss: 3125.2322 - mean_absolute_error: 3125.2322
Epoch 4/100
359291/359291 [==============================] - 6s 16us/step - loss: 2916.4419 - mean_absolute_error: 2916.4419
Epoch 5/100
359291/359291 [==============================] - 6s 17us/step - loss: 2814.0308 - mean_absolute_error: 2814.0308
Epoch 6/100
359291/359291 [==============================] - 6s 16us/step - loss: 2759.8331 - mean_absolute_error: 2759.8331
Epoch 7/100
359291/359291 [==============================] - 6s 16us/step - loss: 2710.2088 - mean_absolute_error: 2710.2088
Epoch 8/100
359291/359291 [==============================] - 6s 16us/step - loss: 2669.1153 - mean_absolute_error: 2669.1153
Epoch 9/100
359291/359291 [==============================] - 9s 24us/step - loss: 2627.0607 - mean_absolute_error: 2627.0607
Epoch 10/100
359291/359291 [==============================] - 10s 29us/step - loss: 2574.0128 - mean_absolute_error: 2574.0128
Epoch 11/100
359291/359291 [==============================] - 8s 24us/step - loss: 2543.9517 - mean_absolute_error: 2543.9517
Epoch 12/100
359291/359291 [==============================] - 12s 32us/step - loss: 2521.5491 - mean_absolute_error: 2521.5491
Epoch 13/100
359291/359291 [==============================] - 7s 20us/step - loss: 2519.8568 - mean_absolute_error: 2519.8568
Epoch 14/100
359291/359291 [==============================] - 8s 21us/step - loss: 2501.9065 - mean_absolute_error: 2501.9065
Epoch 15/100
359291/359291 [==============================] - 8s 23us/step - loss: 2481.1604 - mean_absolute_error: 2481.1604
Epoch 16/100
359291/359291 [==============================] - 8s 24us/step - loss: 2458.2171 - mean_absolute_error: 2458.2171
Epoch 17/100
359291/359291 [==============================] - 6s 16us/step - loss: 2439.3957 - mean_absolute_error: 2439.3957
Epoch 18/100
359291/359291 [==============================] - 6s 17us/step - loss: 2454.3213 - mean_absolute_error: 2454.3213
Epoch 19/100
359291/359291 [==============================] - 7s 19us/step - loss: 2427.0580 - mean_absolute_error: 2427.0580
Epoch 20/100
359291/359291 [==============================] - 8s 22us/step - loss: 2433.8989 - mean_absolute_error: 2433.8989
Epoch 21/100
359291/359291 [==============================] - 6s 15us/step - loss: 2407.1436 - mean_absolute_error: 2407.1436
Epoch 22/100
359291/359291 [==============================] - 6s 16us/step - loss: 2405.2454 - mean_absolute_error: 2405.2454
Epoch 23/100
359291/359291 [==============================] - 5s 13us/step - loss: 2415.3244 - mean_absolute_error: 2415.3244
Epoch 24/100
359291/359291 [==============================] - 7s 18us/step - loss: 2400.2893 - mean_absolute_error: 2400.2893
Epoch 25/100
359291/359291 [==============================] - 6s 18us/step - loss: 2394.6750 - mean_absolute_error: 2394.6750
Epoch 26/100
359291/359291 [==============================] - 9s 24us/step - loss: 2395.1071 - mean_absolute_error: 2395.1071
Epoch 27/100
359291/359291 [==============================] - 6s 16us/step - loss: 2385.4556 - mean_absolute_error: 2385.4556
Epoch 28/100
359291/359291 [==============================] - 5s 14us/step - loss: 2378.4504 - mean_absolute_error: 2378.4504
Epoch 29/100
359291/359291 [==============================] - 7s 19us/step - loss: 2382.4123 - mean_absolute_error: 2382.4123
Epoch 30/100
359291/359291 [==============================] - 6s 17us/step - loss: 2369.9355 - mean_absolute_error: 2369.9355
Epoch 31/100
359291/359291 [==============================] - 5s 14us/step - loss: 2361.8907 - mean_absolute_error: 2361.8907
Epoch 32/100
359291/359291 [==============================] - 5s 13us/step - loss: 2363.8178 - mean_absolute_error: 2363.8178
Epoch 33/100
359291/359291 [==============================] - 5s 15us/step - loss: 2355.9576 - mean_absolute_error: 2355.9576
Epoch 34/100
359291/359291 [==============================] - 5s 13us/step - loss: 2345.4953 - mean_absolute_error: 2345.4953
Epoch 35/100
359291/359291 [==============================] - ETA: 0s - loss: 2361.4324 - mean_absolute_error: 2361.432 - 5s 15us/step - loss: 2360.1522 - mean_absolute_error: 2360.1522
Epoch 36/100
359291/359291 [==============================] - 4s 12us/step - loss: 2342.6248 - mean_absolute_error: 2342.6248
Epoch 37/100
359291/359291 [==============================] - 5s 14us/step - loss: 2345.4850 - mean_absolute_error: 2345.4850
Epoch 38/100
359291/359291 [==============================] - 5s 13us/step - loss: 2341.4549 - mean_absolute_error: 2341.4549
Epoch 39/100
359291/359291 [==============================] - 4s 12us/step - loss: 2336.2688 - mean_absolute_error: 2336.2688
Epoch 40/100
359291/359291 [==============================] - 5s 14us/step - loss: 2352.2132 - mean_absolute_error: 2352.2132
Epoch 41/100
359291/359291 [==============================] - 5s 13us/step - loss: 2322.5607 - mean_absolute_error: 2322.5607
Epoch 42/100
359291/359291 [==============================] - 6s 16us/step - loss: 2349.1367 - mean_absolute_error: 2349.1367
Epoch 43/100
359291/359291 [==============================] - 4s 12us/step - loss: 2328.0820 - mean_absolute_error: 2328.0820
Epoch 44/100
359291/359291 [==============================] - 5s 15us/step - loss: 2324.1417 - mean_absolute_error: 2324.1417
Epoch 45/100
359291/359291 [==============================] - 5s 13us/step - loss: 2332.0757 - mean_absolute_error: 2332.0757
Epoch 46/100
359291/359291 [==============================] - 6s 17us/step - loss: 2320.5313 - mean_absolute_error: 2320.5313
Epoch 47/100
359291/359291 [==============================] - 7s 19us/step - loss: 2332.9258 - mean_absolute_error: 2332.9258
Epoch 48/100
359291/359291 [==============================] - 7s 19us/step - loss: 2320.5281 - mean_absolute_error: 2320.5281
Epoch 49/100
359291/359291 [==============================] - 6s 17us/step - loss: 2318.2858 - mean_absolute_error: 2318.2858
Epoch 50/100
359291/359291 [==============================] - 5s 14us/step - loss: 2316.4834 - mean_absolute_error: 2316.4834
Epoch 51/100
359291/359291 [==============================] - 5s 15us/step - loss: 2320.2183 - mean_absolute_error: 2320.2183
Epoch 52/100
359291/359291 [==============================] - 4s 11us/step - loss: 2307.1900 - mean_absolute_error: 2307.1900
Epoch 53/100
359291/359291 [==============================] - 5s 14us/step - loss: 2311.1822 - mean_absolute_error: 2311.1822
Epoch 54/100
359291/359291 [==============================] - 6s 17us/step - loss: 2297.8141 - mean_absolute_error: 2297.8141
Epoch 55/100
359291/359291 [==============================] - 5s 14us/step - loss: 2299.0664 - mean_absolute_error: 2299.0664
Epoch 56/100
359291/359291 [==============================] - 4s 12us/step - loss: 2307.9185 - mean_absolute_error: 2307.9185
Epoch 57/100
359291/359291 [==============================] - 4s 12us/step - loss: 2300.3242 - mean_absolute_error: 2300.3242
Epoch 58/100
359291/359291 [==============================] - 5s 14us/step - loss: 2302.5757 - mean_absolute_error: 2302.5757
Epoch 59/100
359291/359291 [==============================] - 4s 11us/step - loss: 2286.7378 - mean_absolute_error: 2286.7378
Epoch 60/100
359291/359291 [==============================] - 5s 14us/step - loss: 2290.7238 - mean_absolute_error: 2290.7238
Epoch 61/100
359291/359291 [==============================] - 5s 13us/step - loss: 2292.4077 - mean_absolute_error: 2292.4077
Epoch 62/100
359291/359291 [==============================] - 5s 14us/step - loss: 2295.0735 - mean_absolute_error: 2295.0735
Epoch 63/100
359291/359291 [==============================] - 4s 12us/step - loss: 2296.3476 - mean_absolute_error: 2296.3476
Epoch 64/100
359291/359291 [==============================] - 4s 12us/step - loss: 2288.1710 - mean_absolute_error: 2288.1710
Epoch 65/100

359291/359291 [==============================] - 5s 14us/step - loss: 2292.7411 - mean_absolute_error: 2292.7411
Epoch 66/100
359291/359291 [==============================] - 4s 11us/step - loss: 2294.0384 - mean_absolute_error: 2294.0384
Epoch 67/100
359291/359291 [==============================] - 5s 14us/step - loss: 2281.4754 - mean_absolute_error: 2281.4754
Epoch 68/100
359291/359291 [==============================] - 5s 13us/step - loss: 2285.4997 - mean_absolute_error: 2285.4997
Epoch 69/100
359291/359291 [==============================] - 5s 13us/step - loss: 2298.3071 - mean_absolute_error: 2298.3071
Epoch 70/100
359291/359291 [==============================] - 5s 13us/step - loss: 2274.4151 - mean_absolute_error: 2274.4151
Epoch 71/100
359291/359291 [==============================] - 4s 12us/step - loss: 2280.2976 - mean_absolute_error: 2280.2976
Epoch 72/100
359291/359291 [==============================] - 5s 13us/step - loss: 2270.3897 - mean_absolute_error: 2270.3897
Epoch 73/100
359291/359291 [==============================] - 4s 11us/step - loss: 2272.6431 - mean_absolute_error: 2272.6431
Epoch 74/100
359291/359291 [==============================] - 5s 14us/step - loss: 2285.1131 - mean_absolute_error: 2285.1131
Epoch 75/100
359291/359291 [==============================] - 4s 12us/step - loss: 2285.7040 - mean_absolute_error: 2285.7040
Epoch 76/100
359291/359291 [==============================] - 5s 13us/step - loss: 2273.3251 - mean_absolute_error: 2273.3251
Epoch 77/100
359291/359291 [==============================] - 5s 13us/step - loss: 2273.6099 - mean_absolute_error: 2273.6099
Epoch 78/100
359291/359291 [==============================] - 4s 12us/step - loss: 2261.3683 - mean_absolute_error: 2261.3683
Epoch 79/100
359291/359291 [==============================] - 5s 13us/step - loss: 2277.6968 - mean_absolute_error: 2277.6968
Epoch 80/100
359291/359291 [==============================] - 4s 12us/step - loss: 2272.4723 - mean_absolute_error: 2272.4723
Epoch 81/100
359291/359291 [==============================] - 5s 14us/step - loss: 2263.2279 - mean_absolute_error: 2263.2279
Epoch 82/100
359291/359291 [==============================] - 4s 12us/step - loss: 2262.8070 - mean_absolute_error: 2262.8070
Epoch 83/100
359291/359291 [==============================] - 5s 13us/step - loss: 2251.6719 - mean_absolute_error: 2251.6719
Epoch 84/100
359291/359291 [==============================] - 5s 13us/step - loss: 2264.3602 - mean_absolute_error: 2264.3602
Epoch 85/100
359291/359291 [==============================] - 4s 11us/step - loss: 2268.2052 - mean_absolute_error: 2268.2052
Epoch 86/100
359291/359291 [==============================] - 5s 14us/step - loss: 2247.7344 - mean_absolute_error: 2247.7344
Epoch 87/100
359291/359291 [==============================] - 4s 12us/step - loss: 2256.2861 - mean_absolute_error: 2256.2861
Epoch 88/100
359291/359291 [==============================] - 5s 14us/step - loss: 2250.0519 - mean_absolute_error: 2250.0519
Epoch 89/100
359291/359291 [==============================] - 4s 12us/step - loss: 2252.0498 - mean_absolute_error: 2252.0498
Epoch 90/100
359291/359291 [==============================] - 4s 12us/step - loss: 2257.0357 - mean_absolute_error: 2257.0357
Epoch 91/100
359291/359291 [==============================] - 5s 13us/step - loss: 2249.6950 - mean_absolute_error: 2249.6950
Epoch 92/100
359291/359291 [==============================] - 4s 11us/step - loss: 2249.7074 - mean_absolute_error: 2249.7074
Epoch 93/100
359291/359291 [==============================] - 5s 14us/step - loss: 2249.1900 - mean_absolute_error: 2249.1900
Epoch 94/100
359291/359291 [==============================] - 4s 12us/step - loss: 2247.6831 - mean_absolute_error: 2247.6831
Epoch 95/100
359291/359291 [==============================] - 5s 13us/step - loss: 2248.0768 - mean_absolute_error: 2248.0768
Epoch 96/100
359291/359291 [==============================] - 5s 13us/step - loss: 2243.0974 - mean_absolute_error: 2243.0974
Epoch 97/100
359291/359291 [==============================] - 4s 12us/step - loss: 2244.0708 - mean_absolute_error: 2244.0708
Epoch 98/100
359291/359291 [==============================] - 5s 14us/step - loss: 2245.1206 - mean_absolute_error: 2245.1206
Epoch 99/100
359291/359291 [==============================] - 4s 11us/step - loss: 2249.3719 - mean_absolute_error: 2249.3719
Epoch 100/100
359291/359291 [==============================] - 5s 14us/step - loss: 2239.1489 - mean_absolute_error: 2239.1489
Epoch 1/100
323361/323361 [==============================] - 4s 12us/step - loss: 2239.0665 - mean_absolute_error: 2239.0665
Epoch 2/100
323361/323361 [==============================] - 4s 13us/step - loss: 2249.5521 - mean_absolute_error: 2249.5521
Epoch 3/100
323361/323361 [==============================] - 5s 14us/step - loss: 2241.6604 - mean_absolute_error: 2241.6604
Epoch 4/100
323361/323361 [==============================] - 4s 11us/step - loss: 2240.8793 - mean_absolute_error: 2240.8793
Epoch 5/100
323361/323361 [==============================] - 4s 14us/step - loss: 2245.7300 - mean_absolute_error: 2245.7300
Epoch 6/100
323361/323361 [==============================] - 4s 12us/step - loss: 2234.9360 - mean_absolute_error: 2234.9360
Epoch 7/100
323361/323361 [==============================] - 4s 13us/step - loss: 2225.9640 - mean_absolute_error: 2225.9640
Epoch 8/100
323361/323361 [==============================] - 4s 13us/step - loss: 2245.3455 - mean_absolute_error: 2245.3455
Epoch 9/100
323361/323361 [==============================] - 4s 11us/step - loss: 2237.7447 - mean_absolute_error: 2237.7447
Epoch 10/100
323361/323361 [==============================] - 5s 14us/step - loss: 2221.1025 - mean_absolute_error: 2221.1025
Epoch 11/100
323361/323361 [==============================] - 4s 12us/step - loss: 2239.6341 - mean_absolute_error: 2239.6341
Epoch 12/100
323361/323361 [==============================] - 4s 12us/step - loss: 2227.0540 - mean_absolute_error: 2227.0540
Epoch 13/100
323361/323361 [==============================] - 4s 13us/step - loss: 2229.1558 - mean_absolute_error: 2229.1558
Epoch 14/100
323361/323361 [==============================] - 4s 12us/step - loss: 2232.2064 - mean_absolute_error: 2232.2064
Epoch 15/100
323361/323361 [==============================] - 4s 13us/step - loss: 2219.8092 - mean_absolute_error: 2219.8092
Epoch 16/100
323361/323361 [==============================] - 5s 15us/step - loss: 2242.1029 - mean_absolute_error: 2242.1029
Epoch 17/100
323361/323361 [==============================] - 6s 18us/step - loss: 2232.9485 - mean_absolute_error: 2232.9485
Epoch 18/100
323361/323361 [==============================] - 5s 16us/step - loss: 2225.1642 - mean_absolute_error: 2225.1642
Epoch 19/100
323361/323361 [==============================] - 4s 12us/step - loss: 2233.1778 - mean_absolute_error: 2233.1778
Epoch 20/100
323361/323361 [==============================] - 5s 14us/step - loss: 2222.0602 - mean_absolute_error: 2222.0602
Epoch 21/100
323361/323361 [==============================] - 4s 12us/step - loss: 2221.0616 - mean_absolute_error: 2221.0616
Epoch 22/100
323361/323361 [==============================] - 4s 12us/step - loss: 2219.9744 - mean_absolute_error: 2219.9744
Epoch 23/100
323361/323361 [==============================] - 5s 15us/step - loss: 2218.3510 - mean_absolute_error: 2218.3510
Epoch 24/100
323361/323361 [==============================] - 4s 12us/step - loss: 2216.0823 - mean_absolute_error: 2216.0823
Epoch 25/100
323361/323361 [==============================] - 5s 14us/step - loss: 2225.7907 - mean_absolute_error: 2225.7907
Epoch 26/100
323361/323361 [==============================] - 4s 12us/step - loss: 2224.9603 - mean_absolute_error: 2224.9603
Epoch 27/100
323361/323361 [==============================] - 4s 12us/step - loss: 2218.0111 - mean_absolute_error: 2218.0111
Epoch 28/100
323361/323361 [==============================] - 5s 14us/step - loss: 2217.5365 - mean_absolute_error: 2217.5365
Epoch 29/100
323361/323361 [==============================] - 4s 11us/step - loss: 2224.7881 - mean_absolute_error: 2224.7881
Epoch 30/100

323361/323361 [==============================] - 4s 12us/step - loss: 2219.1860 - mean_absolute_error: 2219.1860
Epoch 31/100
323361/323361 [==============================] - 5s 14us/step - loss: 2218.7196 - mean_absolute_error: 2218.7196
Epoch 32/100
323361/323361 [==============================] - 3s 10us/step - loss: 2206.6548 - mean_absolute_error: 2206.6548
Epoch 33/100
323361/323361 [==============================] - 4s 12us/step - loss: 2214.1031 - mean_absolute_error: 2214.1031
Epoch 34/100
323361/323361 [==============================] - 4s 13us/step - loss: 2218.2666 - mean_absolute_error: 2218.2666
Epoch 35/100
323361/323361 [==============================] - 4s 11us/step - loss: 2227.7748 - mean_absolute_error: 2227.7748
Epoch 36/100
323361/323361 [==============================] - 3s 9us/step - loss: 2216.3115 - mean_absolute_error: 2216.3115
Epoch 37/100
323361/323361 [==============================] - 3s 10us/step - loss: 2213.2624 - mean_absolute_error: 2213.2624
Epoch 38/100
323361/323361 [==============================] - 4s 13us/step - loss: 2227.3294 - mean_absolute_error: 2227.3294
Epoch 39/100
323361/323361 [==============================] - 5s 15us/step - loss: 2210.3061 - mean_absolute_error: 2210.3061
Epoch 40/100
323361/323361 [==============================] - 3s 10us/step - loss: 2212.5508 - mean_absolute_error: 2212.5508
Epoch 41/100
323361/323361 [==============================] - 3s 8us/step - loss: 2210.8213 - mean_absolute_error: 2210.8213
Epoch 42/100
323361/323361 [==============================] - 3s 8us/step - loss: 2207.2532 - mean_absolute_error: 2207.2532
Epoch 43/100
323361/323361 [==============================] - 3s 8us/step - loss: 2208.4265 - mean_absolute_error: 2208.4265
Epoch 44/100
323361/323361 [==============================] - 3s 10us/step - loss: 2211.7965 - mean_absolute_error: 2211.7965
Epoch 45/100
323361/323361 [==============================] - 5s 14us/step - loss: 2220.8670 - mean_absolute_error: 2220.8670
Epoch 46/100
323361/323361 [==============================] - 4s 13us/step - loss: 2215.6651 - mean_absolute_error: 2215.6651
Epoch 47/100
323361/323361 [==============================] - 3s 10us/step - loss: 2207.8921 - mean_absolute_error: 2207.8921
Epoch 48/100
323361/323361 [==============================] - 3s 9us/step - loss: 2208.3180 - mean_absolute_error: 2208.3180
Epoch 49/100
323361/323361 [==============================] - 3s 9us/step - loss: 2199.2523 - mean_absolute_error: 2199.2523
Epoch 50/100
323361/323361 [==============================] - 3s 9us/step - loss: 2219.2118 - mean_absolute_error: 2219.2118
Epoch 51/100
323361/323361 [==============================] - 3s 9us/step - loss: 2199.6555 - mean_absolute_error: 2199.6555
Epoch 52/100
323361/323361 [==============================] - 3s 9us/step - loss: 2203.2763 - mean_absolute_error: 2203.2763
Epoch 53/100
323361/323361 [==============================] - 3s 9us/step - loss: 2197.8647 - mean_absolute_error: 2197.8647
Epoch 54/100
323361/323361 [==============================] - 3s 9us/step - loss: 2205.9616 - mean_absolute_error: 2205.9616
Epoch 55/100
323361/323361 [==============================] - 3s 10us/step - loss: 2201.5600 - mean_absolute_error: 2201.5600
Epoch 56/100
323361/323361 [==============================] - 4s 13us/step - loss: 2204.6238 - mean_absolute_error: 2204.6238
Epoch 57/100
323361/323361 [==============================] - 4s 12us/step - loss: 2206.9210 - mean_absolute_error: 2206.9210
Epoch 58/100
323361/323361 [==============================] - 3s 9us/step - loss: 2200.9444 - mean_absolute_error: 2200.9444
Epoch 59/100
323361/323361 [==============================] - 3s 9us/step - loss: 2198.4213 - mean_absolute_error: 2198.4213
Epoch 60/100
323361/323361 [==============================] - 3s 9us/step - loss: 2206.7055 - mean_absolute_error: 2206.7055
Epoch 61/100
323361/323361 [==============================] - 3s 9us/step - loss: 2203.4887 - mean_absolute_error: 2203.4887
Epoch 62/100
323361/323361 [==============================] - 3s 9us/step - loss: 2207.4716 - mean_absolute_error: 2207.4716
Epoch 63/100
323361/323361 [==============================] - 3s 9us/step - loss: 2194.6964 - mean_absolute_error: 2194.6964
Epoch 64/100
323361/323361 [==============================] - 3s 9us/step - loss: 2204.2180 - mean_absolute_error: 2204.2180
Epoch 65/100
323361/323361 [==============================] - 3s 8us/step - loss: 2205.0362 - mean_absolute_error: 2205.0362
Epoch 66/100
323361/323361 [==============================] - 3s 8us/step - loss: 2197.5639 - mean_absolute_error: 2197.5639
Epoch 67/100
323361/323361 [==============================] - 3s 8us/step - loss: 2207.7909 - mean_absolute_error: 2207.7909
Epoch 68/100
323361/323361 [==============================] - 3s 9us/step - loss: 2200.0704 - mean_absolute_error: 2200.0704
Epoch 69/100
323361/323361 [==============================] - 3s 9us/step - loss: 2195.4042 - mean_absolute_error: 2195.4042
Epoch 70/100
323361/323361 [==============================] - 3s 9us/step - loss: 2203.2931 - mean_absolute_error: 2203.2931
Epoch 71/100
323361/323361 [==============================] - 3s 9us/step - loss: 2196.3522 - mean_absolute_error: 2196.3522
Epoch 72/100
323361/323361 [==============================] - 3s 9us/step - loss: 2202.8988 - mean_absolute_error: 2202.8988
Epoch 73/100
323361/323361 [==============================] - 3s 9us/step - loss: 2194.7307 - mean_absolute_error: 2194.7307
Epoch 74/100
323361/323361 [==============================] - 3s 9us/step - loss: 2205.4106 - mean_absolute_error: 2205.4106
Epoch 75/100
323361/323361 [==============================] - 3s 9us/step - loss: 2191.3010 - mean_absolute_error: 2191.3010
Epoch 76/100
323361/323361 [==============================] - 4s 12us/step - loss: 2202.0952 - mean_absolute_error: 2202.0952
Epoch 77/100
323361/323361 [==============================] - 4s 13us/step - loss: 2193.8624 - mean_absolute_error: 2193.8624
Epoch 78/100
323361/323361 [==============================] - 3s 10us/step - loss: 2199.6571 - mean_absolute_error: 2199.6571
Epoch 79/100
323361/323361 [==============================] - 3s 9us/step - loss: 2190.1513 - mean_absolute_error: 2190.1513
Epoch 80/100
323361/323361 [==============================] - 3s 8us/step - loss: 2195.3773 - mean_absolute_error: 2195.3773
Epoch 81/100
323361/323361 [==============================] - 3s 8us/step - loss: 2188.1091 - mean_absolute_error: 2188.1091
Epoch 82/100
323361/323361 [==============================] - 3s 8us/step - loss: 2199.5049 - mean_absolute_error: 2199.5049
Epoch 83/100
323361/323361 [==============================] - 3s 8us/step - loss: 2186.0493 - mean_absolute_error: 2186.0493
Epoch 84/100
323361/323361 [==============================] - 3s 9us/step - loss: 2190.4574 - mean_absolute_error: 2190.4574
Epoch 85/100
323361/323361 [==============================] - 3s 9us/step - loss: 2200.1986 - mean_absolute_error: 2200.1986
Epoch 86/100
323361/323361 [==============================] - 3s 9us/step - loss: 2190.5195 - mean_absolute_error: 2190.5195
Epoch 87/100
323361/323361 [==============================] - 3s 9us/step - loss: 2191.8635 - mean_absolute_error: 2191.8635
Epoch 88/100
323361/323361 [==============================] - 3s 9us/step - loss: 2193.9655 - mean_absolute_error: 2193.9655
Epoch 89/100
323361/323361 [==============================] - 3s 9us/step - loss: 2189.3487 - mean_absolute_error: 2189.3487
Epoch 90/100
323361/323361 [==============================] - 3s 9us/step - loss: 2184.8208 - mean_absolute_error: 2184.8208
Epoch 91/100
323361/323361 [==============================] - 3s 9us/step - loss: 2180.9502 - mean_absolute_error: 2180.9502A: 0s - loss: 2182.2608 - mean_absolute_error: 2182.2
Epoch 92/100
323361/323361 [==============================] - 3s 9us/step - loss: 2205.2906 - mean_absolute_error: 2205.2906
Epoch 93/100
323361/323361 [==============================] - 3s 8us/step - loss: 2189.0490 - mean_absolute_error: 2189.0490
Epoch 94/100
323361/323361 [==============================] - 3s 8us/step - loss: 2178.5951 - mean_absolute_error: 2178.5951
Epoch 95/100

323361/323361 [==============================] - 3s 8us/step - loss: 2193.7720 - mean_absolute_error: 2193.7720
Epoch 96/100
323361/323361 [==============================] - 3s 9us/step - loss: 2190.7295 - mean_absolute_error: 2190.7295
Epoch 97/100
323361/323361 [==============================] - 3s 9us/step - loss: 2190.0328 - mean_absolute_error: 2190.0328
Epoch 98/100
323361/323361 [==============================] - 3s 9us/step - loss: 2179.3322 - mean_absolute_error: 2179.3322
Epoch 99/100
323361/323361 [==============================] - 3s 9us/step - loss: 2185.7819 - mean_absolute_error: 2185.7819
Epoch 100/100
323361/323361 [==============================] - 4s 13us/step - loss: 2187.4188 - mean_absolute_error: 2187.4188
Epoch 1/100
359291/359291 [==============================] - 5s 13us/step - loss: 3853.4586 - mean_absolute_error: 3853.4586
Epoch 2/100
359291/359291 [==============================] - 4s 10us/step - loss: 3368.0934 - mean_absolute_error: 3368.0934
Epoch 3/100
359291/359291 [==============================] - 4s 10us/step - loss: 3069.5512 - mean_absolute_error: 3069.5512
Epoch 4/100
359291/359291 [==============================] - 3s 8us/step - loss: 2906.4652 - mean_absolute_error: 2906.4652
Epoch 5/100
359291/359291 [==============================] - 3s 9us/step - loss: 2795.7294 - mean_absolute_error: 2795.7294
Epoch 6/100
359291/359291 [==============================] - 3s 9us/step - loss: 2747.3417 - mean_absolute_error: 2747.3417
Epoch 7/100
359291/359291 [==============================] - 3s 9us/step - loss: 2698.9654 - mean_absolute_error: 2698.9654
Epoch 8/100
359291/359291 [==============================] - 3s 9us/step - loss: 2670.1714 - mean_absolute_error: 2670.1714
Epoch 9/100
359291/359291 [==============================] - 3s 9us/step - loss: 2624.2917 - mean_absolute_error: 2624.2917
Epoch 10/100
359291/359291 [==============================] - 3s 9us/step - loss: 2584.4986 - mean_absolute_error: 2584.4986
Epoch 11/100
359291/359291 [==============================] - 3s 9us/step - loss: 2575.5508 - mean_absolute_error: 2575.5508
Epoch 12/100
359291/359291 [==============================] - 3s 9us/step - loss: 2528.8650 - mean_absolute_error: 2528.8650
Epoch 13/100
359291/359291 [==============================] - 3s 9us/step - loss: 2505.0275 - mean_absolute_error: 2505.0275
Epoch 14/100
359291/359291 [==============================] - 3s 9us/step - loss: 2497.1174 - mean_absolute_error: 2497.1174
Epoch 15/100
359291/359291 [==============================] - 3s 9us/step - loss: 2469.6790 - mean_absolute_error: 2469.6790
Epoch 16/100
359291/359291 [==============================] - 3s 9us/step - loss: 2450.2863 - mean_absolute_error: 2450.2863
Epoch 17/100
359291/359291 [==============================] - 3s 9us/step - loss: 2446.7842 - mean_absolute_error: 2446.7842
Epoch 18/100
359291/359291 [==============================] - 3s 9us/step - loss: 2428.0212 - mean_absolute_error: 2428.0212
Epoch 19/100
359291/359291 [==============================] - 3s 8us/step - loss: 2433.0259 - mean_absolute_error: 2433.0259
Epoch 20/100
359291/359291 [==============================] - 4s 12us/step - loss: 2424.7696 - mean_absolute_error: 2424.7696
Epoch 21/100
359291/359291 [==============================] - 5s 15us/step - loss: 2418.7664 - mean_absolute_error: 2418.7664
Epoch 22/100
359291/359291 [==============================] - 4s 11us/step - loss: 2419.9059 - mean_absolute_error: 2419.9059
Epoch 23/100
359291/359291 [==============================] - 3s 9us/step - loss: 2398.6241 - mean_absolute_error: 2398.6241
Epoch 24/100
359291/359291 [==============================] - 3s 9us/step - loss: 2399.5271 - mean_absolute_error: 2399.5271
Epoch 25/100
359291/359291 [==============================] - 3s 9us/step - loss: 2392.4221 - mean_absolute_error: 2392.4221
Epoch 26/100
359291/359291 [==============================] - 3s 9us/step - loss: 2382.2681 - mean_absolute_error: 2382.2681
Epoch 27/100
359291/359291 [==============================] - 3s 9us/step - loss: 2372.7935 - mean_absolute_error: 2372.7935
Epoch 28/100
359291/359291 [==============================] - 3s 9us/step - loss: 2383.3211 - mean_absolute_error: 2383.3211
Epoch 29/100
359291/359291 [==============================] - 3s 9us/step - loss: 2376.7400 - mean_absolute_error: 2376.7400
Epoch 30/100
359291/359291 [==============================] - 3s 9us/step - loss: 2367.7470 - mean_absolute_error: 2367.7470
Epoch 31/100
359291/359291 [==============================] - 3s 9us/step - loss: 2366.4995 - mean_absolute_error: 2366.4995
Epoch 32/100
359291/359291 [==============================] - 3s 9us/step - loss: 2364.8905 - mean_absolute_error: 2364.8905
Epoch 33/100
359291/359291 [==============================] - 3s 9us/step - loss: 2359.7519 - mean_absolute_error: 2359.7519
Epoch 34/100
359291/359291 [==============================] - 3s 9us/step - loss: 2372.8517 - mean_absolute_error: 2372.8517
Epoch 35/100
359291/359291 [==============================] - 3s 9us/step - loss: 2353.1614 - mean_absolute_error: 2353.1614
Epoch 36/100
359291/359291 [==============================] - 3s 9us/step - loss: 2346.0648 - mean_absolute_error: 2346.0648
Epoch 37/100
359291/359291 [==============================] - 3s 9us/step - loss: 2356.8007 - mean_absolute_error: 2356.8007
Epoch 38/100
359291/359291 [==============================] - 3s 9us/step - loss: 2349.7690 - mean_absolute_error: 2349.7690
Epoch 39/100
359291/359291 [==============================] - 3s 9us/step - loss: 2342.8200 - mean_absolute_error: 2342.8200
Epoch 40/100
359291/359291 [==============================] - 4s 10us/step - loss: 2340.5160 - mean_absolute_error: 2340.5160
Epoch 41/100
359291/359291 [==============================] - 5s 14us/step - loss: 2327.8107 - mean_absolute_error: 2327.8107
Epoch 42/100
359291/359291 [==============================] - 4s 12us/step - loss: 2339.6129 - mean_absolute_error: 2339.6129
Epoch 43/100
359291/359291 [==============================] - 4s 10us/step - loss: 2331.9423 - mean_absolute_error: 2331.9423
Epoch 44/100
359291/359291 [==============================] - 3s 9us/step - loss: 2325.6853 - mean_absolute_error: 2325.6853
Epoch 45/100
359291/359291 [==============================] - 3s 9us/step - loss: 2325.7387 - mean_absolute_error: 2325.7387
Epoch 46/100
359291/359291 [==============================] - 3s 9us/step - loss: 2317.9992 - mean_absolute_error: 2317.9992
Epoch 47/100
359291/359291 [==============================] - 3s 9us/step - loss: 2331.5109 - mean_absolute_error: 2331.5109
Epoch 48/100
359291/359291 [==============================] - 3s 8us/step - loss: 2327.2186 - mean_absolute_error: 2327.2186
Epoch 49/100
359291/359291 [==============================] - 3s 9us/step - loss: 2320.6079 - mean_absolute_error: 2320.6079
Epoch 50/100
359291/359291 [==============================] - 3s 9us/step - loss: 2326.8948 - mean_absolute_error: 2326.8948
Epoch 51/100
359291/359291 [==============================] - 3s 9us/step - loss: 2306.0531 - mean_absolute_error: 2306.0531
Epoch 52/100
359291/359291 [==============================] - 3s 9us/step - loss: 2321.5870 - mean_absolute_error: 2321.5870
Epoch 53/100
359291/359291 [==============================] - 3s 9us/step - loss: 2298.0014 - mean_absolute_error: 2298.0014
Epoch 54/100
359291/359291 [==============================] - 3s 9us/step - loss: 2311.0356 - mean_absolute_error: 2311.0356
Epoch 55/100
359291/359291 [==============================] - 3s 9us/step - loss: 2309.4206 - mean_absolute_error: 2309.4206
Epoch 56/100
359291/359291 [==============================] - 3s 9us/step - loss: 2287.9893 - mean_absolute_error: 2287.9893
Epoch 57/100
359291/359291 [==============================] - 4s 10us/step - loss: 2303.7513 - mean_absolute_error: 2303.7513
Epoch 58/100
359291/359291 [==============================] - 3s 10us/step - loss: 2301.7378 - mean_absolute_error: 2301.7378
Epoch 59/100
359291/359291 [==============================] - 4s 10us/step - loss: 2306.9769 - mean_absolute_error: 2306.9769
Epoch 60/100

359291/359291 [==============================] - 4s 11us/step - loss: 2297.9920 - mean_absolute_error: 2297.9920
Epoch 61/100
359291/359291 [==============================] - 5s 14us/step - loss: 2297.5017 - mean_absolute_error: 2297.5017
Epoch 62/100
359291/359291 [==============================] - 5s 13us/step - loss: 2299.4231 - mean_absolute_error: 2299.4231
Epoch 63/100
359291/359291 [==============================] - 5s 14us/step - loss: 2298.7828 - mean_absolute_error: 2298.7828
Epoch 64/100
359291/359291 [==============================] - 5s 14us/step - loss: 2286.9826 - mean_absolute_error: 2286.9826
Epoch 65/100
359291/359291 [==============================] - 5s 15us/step - loss: 2291.4653 - mean_absolute_error: 2291.4653
Epoch 66/100
359291/359291 [==============================] - 5s 14us/step - loss: 2291.3823 - mean_absolute_error: 2291.3823
Epoch 67/100
359291/359291 [==============================] - 5s 14us/step - loss: 2282.9686 - mean_absolute_error: 2282.9686
Epoch 68/100
359291/359291 [==============================] - 5s 14us/step - loss: 2279.3456 - mean_absolute_error: 2279.3456
Epoch 69/100
359291/359291 [==============================] - 5s 14us/step - loss: 2289.4967 - mean_absolute_error: 2289.4967
Epoch 70/100
359291/359291 [==============================] - 5s 14us/step - loss: 2300.1966 - mean_absolute_error: 2300.1966
Epoch 71/100
359291/359291 [==============================] - 5s 14us/step - loss: 2277.5772 - mean_absolute_error: 2277.5772
Epoch 72/100
359291/359291 [==============================] - 5s 14us/step - loss: 2285.9574 - mean_absolute_error: 2285.9574
Epoch 73/100
359291/359291 [==============================] - 5s 14us/step - loss: 2273.0846 - mean_absolute_error: 2273.0846
Epoch 74/100
359291/359291 [==============================] - 6s 18us/step - loss: 2273.7132 - mean_absolute_error: 2273.7132
Epoch 75/100
359291/359291 [==============================] - 8s 23us/step - loss: 2264.3661 - mean_absolute_error: 2264.3661
Epoch 76/100
359291/359291 [==============================] - 5s 14us/step - loss: 2286.1080 - mean_absolute_error: 2286.1080
Epoch 77/100
359291/359291 [==============================] - 7s 21us/step - loss: 2276.4046 - mean_absolute_error: 2276.4046
Epoch 78/100
359291/359291 [==============================] - 9s 24us/step - loss: 2264.8705 - mean_absolute_error: 2264.8705
Epoch 79/100
359291/359291 [==============================] - 9s 24us/step - loss: 2268.3377 - mean_absolute_error: 2268.3377
Epoch 80/100
359291/359291 [==============================] - 6s 17us/step - loss: 2270.9008 - mean_absolute_error: 2270.9008
Epoch 81/100
359291/359291 [==============================] - 7s 20us/step - loss: 2275.0282 - mean_absolute_error: 2275.0282
Epoch 82/100
359291/359291 [==============================] - 7s 19us/step - loss: 2271.6450 - mean_absolute_error: 2271.6450
Epoch 83/100
359291/359291 [==============================] - 8s 24us/step - loss: 2254.7636 - mean_absolute_error: 2254.7636
Epoch 84/100
359291/359291 [==============================] - 8s 21us/step - loss: 2257.2020 - mean_absolute_error: 2257.2020
Epoch 85/100
359291/359291 [==============================] - 7s 20us/step - loss: 2272.6366 - mean_absolute_error: 2272.6366
Epoch 86/100
359291/359291 [==============================] - 8s 22us/step - loss: 2262.4141 - mean_absolute_error: 2262.4141
Epoch 87/100
359291/359291 [==============================] - 7s 19us/step - loss: 2256.9532 - mean_absolute_error: 2256.9532
Epoch 88/100
359291/359291 [==============================] - 8s 23us/step - loss: 2261.0851 - mean_absolute_error: 2261.0851
Epoch 89/100
359291/359291 [==============================] - 7s 19us/step - loss: 2251.6855 - mean_absolute_error: 2251.6855
Epoch 90/100
359291/359291 [==============================] - 8s 23us/step - loss: 2258.0479 - mean_absolute_error: 2258.0479
Epoch 91/100
359291/359291 [==============================] - 7s 20us/step - loss: 2257.8942 - mean_absolute_error: 2257.8942
Epoch 92/100
359291/359291 [==============================] - 10s 29us/step - loss: 2261.6724 - mean_absolute_error: 2261.6724
Epoch 93/100
359291/359291 [==============================] - 7s 20us/step - loss: 2237.4619 - mean_absolute_error: 2237.4619
Epoch 94/100
359291/359291 [==============================] - 10s 27us/step - loss: 2254.8665 - mean_absolute_error: 2254.8665
Epoch 95/100
359291/359291 [==============================] - 8s 22us/step - loss: 2249.6146 - mean_absolute_error: 2249.6146
Epoch 96/100
359291/359291 [==============================] - 9s 25us/step - loss: 2261.2138 - mean_absolute_error: 2261.2138
Epoch 97/100
359291/359291 [==============================] - 8s 23us/step - loss: 2249.4838 - mean_absolute_error: 2249.4838
Epoch 98/100
359291/359291 [==============================] - 8s 24us/step - loss: 2233.5227 - mean_absolute_error: 2233.5227
Epoch 99/100
359291/359291 [==============================] - 8s 23us/step - loss: 2249.8852 - mean_absolute_error: 2249.8852
Epoch 100/100
359291/359291 [==============================] - 9s 26us/step - loss: 2239.1741 - mean_absolute_error: 2239.1741
Epoch 1/100
323362/323362 [==============================] - 9s 28us/step - loss: 2244.5310 - mean_absolute_error: 2244.5310
Epoch 2/100
323362/323362 [==============================] - 6s 20us/step - loss: 2248.5607 - mean_absolute_error: 2248.5607
Epoch 3/100
323362/323362 [==============================] - 5s 15us/step - loss: 2238.1756 - mean_absolute_error: 2238.1756
Epoch 4/100
323362/323362 [==============================] - 5s 15us/step - loss: 2235.8388 - mean_absolute_error: 2235.8388
Epoch 5/100
323362/323362 [==============================] - 5s 16us/step - loss: 2235.3334 - mean_absolute_error: 2235.3334
Epoch 6/100
323362/323362 [==============================] - 9s 27us/step - loss: 2237.0944 - mean_absolute_error: 2237.0944
Epoch 7/100
323362/323362 [==============================] - 7s 21us/step - loss: 2228.1306 - mean_absolute_error: 2228.1306
Epoch 8/100
323362/323362 [==============================] - 8s 26us/step - loss: 2224.1884 - mean_absolute_error: 2224.1884
Epoch 9/100
323362/323362 [==============================] - 7s 20us/step - loss: 2239.5429 - mean_absolute_error: 2239.5429
Epoch 10/100
323362/323362 [==============================] - 8s 25us/step - loss: 2229.0897 - mean_absolute_error: 2229.0897
Epoch 11/100
323362/323362 [==============================] - 6s 20us/step - loss: 2228.1382 - mean_absolute_error: 2228.1382
Epoch 12/100
323362/323362 [==============================] - 8s 24us/step - loss: 2223.8270 - mean_absolute_error: 2223.8270
Epoch 13/100
323362/323362 [==============================] - 7s 22us/step - loss: 2229.8372 - mean_absolute_error: 2229.8372
Epoch 14/100
323362/323362 [==============================] - 9s 27us/step - loss: 2227.9071 - mean_absolute_error: 2227.9071
Epoch 15/100
323362/323362 [==============================] - 7s 20us/step - loss: 2237.2697 - mean_absolute_error: 2237.2697
Epoch 16/100
323362/323362 [==============================] - 8s 26us/step - loss: 2230.7950 - mean_absolute_error: 2230.7950
Epoch 17/100
323362/323362 [==============================] - 8s 23us/step - loss: 2229.4502 - mean_absolute_error: 2229.4502
Epoch 18/100
323362/323362 [==============================] - 7s 22us/step - loss: 2224.3731 - mean_absolute_error: 2224.3731
Epoch 19/100
323362/323362 [==============================] - 7s 22us/step - loss: 2224.1738 - mean_absolute_error: 2224.1738
Epoch 20/100
323362/323362 [==============================] - 8s 23us/step - loss: 2225.1608 - mean_absolute_error: 2225.1608
Epoch 21/100
323362/323362 [==============================] - 7s 23us/step - loss: 2220.7432 - mean_absolute_error: 2220.7432
Epoch 22/100
323362/323362 [==============================] - 8s 24us/step - loss: 2225.1185 - mean_absolute_error: 2225.1185
Epoch 23/100
323362/323362 [==============================] - 8s 26us/step - loss: 2226.0200 - mean_absolute_error: 2226.0200
Epoch 24/100
323362/323362 [==============================] - 5s 15us/step - loss: 2221.4161 - mean_absolute_error: 2221.4161
Epoch 25/100

323362/323362 [==============================] - 8s 24us/step - loss: 2223.3391 - mean_absolute_error: 2223.3391
Epoch 26/100
323362/323362 [==============================] - 7s 20us/step - loss: 2217.3321 - mean_absolute_error: 2217.3321
Epoch 27/100
323362/323362 [==============================] - 8s 26us/step - loss: 2226.6613 - mean_absolute_error: 2226.6613
Epoch 28/100
323362/323362 [==============================] - 7s 21us/step - loss: 2222.6296 - mean_absolute_error: 2222.6296
Epoch 29/100
323362/323362 [==============================] - 6s 20us/step - loss: 2231.4120 - mean_absolute_error: 2231.4120
Epoch 30/100
323362/323362 [==============================] - 4s 12us/step - loss: 2214.0306 - mean_absolute_error: 2214.0306
Epoch 31/100
323362/323362 [==============================] - 5s 15us/step - loss: 2220.6784 - mean_absolute_error: 2220.6784
Epoch 32/100
323362/323362 [==============================] - 7s 22us/step - loss: 2215.4453 - mean_absolute_error: 2215.4453
Epoch 33/100
323362/323362 [==============================] - 8s 24us/step - loss: 2221.2588 - mean_absolute_error: 2221.2588
Epoch 34/100
323362/323362 [==============================] - 6s 20us/step - loss: 2230.9889 - mean_absolute_error: 2230.9889
Epoch 35/100
323362/323362 [==============================] - 8s 26us/step - loss: 2219.3140 - mean_absolute_error: 2219.3140
Epoch 36/100
323362/323362 [==============================] - 7s 21us/step - loss: 2222.0881 - mean_absolute_error: 2222.0881
Epoch 37/100
323362/323362 [==============================] - 7s 22us/step - loss: 2208.6163 - mean_absolute_error: 2208.6163
Epoch 38/100
323362/323362 [==============================] - 5s 16us/step - loss: 2209.7681 - mean_absolute_error: 2209.7681
Epoch 39/100
323362/323362 [==============================] - 7s 22us/step - loss: 2220.6123 - mean_absolute_error: 2220.6123
Epoch 40/100
323362/323362 [==============================] - 7s 23us/step - loss: 2213.8279 - mean_absolute_error: 2213.8279
Epoch 41/100
323362/323362 [==============================] - 8s 23us/step - loss: 2207.6877 - mean_absolute_error: 2207.6877
Epoch 42/100
323362/323362 [==============================] - 8s 24us/step - loss: 2214.8100 - mean_absolute_error: 2214.8100
Epoch 43/100
323362/323362 [==============================] - 7s 22us/step - loss: 2213.8623 - mean_absolute_error: 2213.8623
Epoch 44/100
323362/323362 [==============================] - 8s 26us/step - loss: 2213.8390 - mean_absolute_error: 2213.8390
Epoch 45/100
323362/323362 [==============================] - 7s 22us/step - loss: 2204.6321 - mean_absolute_error: 2204.6321
Epoch 46/100
323362/323362 [==============================] - 9s 29us/step - loss: 2206.3359 - mean_absolute_error: 2206.3359
Epoch 47/100
323362/323362 [==============================] - 7s 23us/step - loss: 2210.6058 - mean_absolute_error: 2210.6058
Epoch 48/100
323362/323362 [==============================] - 8s 26us/step - loss: 2216.2800 - mean_absolute_error: 2216.2800
Epoch 49/100
323362/323362 [==============================] - 7s 21us/step - loss: 2219.0794 - mean_absolute_error: 2219.0794
Epoch 50/100
323362/323362 [==============================] - 8s 24us/step - loss: 2208.0283 - mean_absolute_error: 2208.0283
Epoch 51/100
323362/323362 [==============================] - 7s 21us/step - loss: 2202.6107 - mean_absolute_error: 2202.6107
Epoch 52/100
323362/323362 [==============================] - 8s 25us/step - loss: 2201.7616 - mean_absolute_error: 2201.7616
Epoch 53/100
323362/323362 [==============================] - 7s 21us/step - loss: 2211.5794 - mean_absolute_error: 2211.5794
Epoch 54/100
323362/323362 [==============================] - 8s 26us/step - loss: 2206.6316 - mean_absolute_error: 2206.6316
Epoch 55/100
323362/323362 [==============================] - 7s 23us/step - loss: 2198.8274 - mean_absolute_error: 2198.8274
Epoch 56/100
323362/323362 [==============================] - 8s 25us/step - loss: 2202.5569 - mean_absolute_error: 2202.5569
Epoch 57/100
323362/323362 [==============================] - 7s 21us/step - loss: 2209.3536 - mean_absolute_error: 2209.3536
Epoch 58/100
323362/323362 [==============================] - 9s 27us/step - loss: 2200.8732 - mean_absolute_error: 2200.8732
Epoch 59/100
323362/323362 [==============================] - 7s 23us/step - loss: 2211.0358 - mean_absolute_error: 2211.0358
Epoch 60/100
323362/323362 [==============================] - 8s 25us/step - loss: 2205.6367 - mean_absolute_error: 2205.6367
Epoch 61/100
323362/323362 [==============================] - 7s 22us/step - loss: 2190.6952 - mean_absolute_error: 2190.6952
Epoch 62/100
323362/323362 [==============================] - 8s 25us/step - loss: 2194.4780 - mean_absolute_error: 2194.4780
Epoch 63/100
323362/323362 [==============================] - 7s 22us/step - loss: 2194.9209 - mean_absolute_error: 2194.9209
Epoch 64/100
323362/323362 [==============================] - 8s 25us/step - loss: 2208.9159 - mean_absolute_error: 2208.9159
Epoch 65/100
323362/323362 [==============================] - 7s 23us/step - loss: 2197.3675 - mean_absolute_error: 2197.3675
Epoch 66/100
323362/323362 [==============================] - 7s 22us/step - loss: 2192.4965 - mean_absolute_error: 2192.4965
Epoch 67/100
323362/323362 [==============================] - 4s 13us/step - loss: 2197.7000 - mean_absolute_error: 2197.7000
Epoch 68/100
323362/323362 [==============================] - 7s 22us/step - loss: 2195.8772 - mean_absolute_error: 2195.8772
Epoch 69/100
323362/323362 [==============================] - 8s 25us/step - loss: 2188.6943 - mean_absolute_error: 2188.6943
Epoch 70/100
323362/323362 [==============================] - 8s 24us/step - loss: 2195.8232 - mean_absolute_error: 2195.8232
Epoch 71/100
323362/323362 [==============================] - 8s 24us/step - loss: 2194.9205 - mean_absolute_error: 2194.9205
Epoch 72/100
323362/323362 [==============================] - 8s 25us/step - loss: 2201.3906 - mean_absolute_error: 2201.3906
Epoch 73/100
323362/323362 [==============================] - 8s 25us/step - loss: 2196.8842 - mean_absolute_error: 2196.8842
Epoch 74/100
323362/323362 [==============================] - 7s 22us/step - loss: 2195.5638 - mean_absolute_error: 2195.5638
Epoch 75/100
323362/323362 [==============================] - 8s 24us/step - loss: 2189.9559 - mean_absolute_error: 2189.9559
Epoch 76/100
323362/323362 [==============================] - 7s 22us/step - loss: 2191.4302 - mean_absolute_error: 2191.4302
Epoch 77/100
323362/323362 [==============================] - 9s 27us/step - loss: 2195.1567 - mean_absolute_error: 2195.1567
Epoch 78/100
323362/323362 [==============================] - 7s 23us/step - loss: 2190.1275 - mean_absolute_error: 2190.1275
Epoch 79/100
323362/323362 [==============================] - 8s 26us/step - loss: 2194.3352 - mean_absolute_error: 2194.3352
Epoch 80/100
323362/323362 [==============================] - 7s 21us/step - loss: 2192.6224 - mean_absolute_error: 2192.6224
Epoch 81/100
323362/323362 [==============================] - 9s 27us/step - loss: 2212.8070 - mean_absolute_error: 2212.8070
Epoch 82/100
323362/323362 [==============================] - 7s 21us/step - loss: 2191.1637 - mean_absolute_error: 2191.1637
Epoch 83/100
323362/323362 [==============================] - 9s 29us/step - loss: 2188.7106 - mean_absolute_error: 2188.7106
Epoch 84/100
323362/323362 [==============================] - 5s 17us/step - loss: 2185.2511 - mean_absolute_error: 2185.2511
Epoch 85/100
323362/323362 [==============================] - 5s 17us/step - loss: 2189.0277 - mean_absolute_error: 2189.0277
Epoch 86/100
323362/323362 [==============================] - 4s 14us/step - loss: 2186.5188 - mean_absolute_error: 2186.5188
Epoch 87/100
323362/323362 [==============================] - 5s 16us/step - loss: 2188.5529 - mean_absolute_error: 2188.5529
Epoch 88/100
323362/323362 [==============================] - 4s 13us/step - loss: 2190.4406 - mean_absolute_error: 2190.4406
Epoch 89/100
323362/323362 [==============================] - 4s 14us/step - loss: 2186.2257 - mean_absolute_error: 2186.2257
Epoch 90/100

323362/323362 [==============================] - 5s 14us/step - loss: 2188.9571 - mean_absolute_error: 2188.9571
Epoch 91/100
323362/323362 [==============================] - 4s 12us/step - loss: 2177.9482 - mean_absolute_error: 2177.9482
Epoch 92/100
323362/323362 [==============================] - 5s 15us/step - loss: 2181.9991 - mean_absolute_error: 2181.9991
Epoch 93/100
323362/323362 [==============================] - 4s 14us/step - loss: 2187.8191 - mean_absolute_error: 2187.8191
Epoch 94/100
323362/323362 [==============================] - 5s 15us/step - loss: 2176.0964 - mean_absolute_error: 2176.0964
Epoch 95/100
323362/323362 [==============================] - 4s 13us/step - loss: 2187.6957 - mean_absolute_error: 2187.6957
Epoch 96/100
323362/323362 [==============================] - 5s 15us/step - loss: 2185.2516 - mean_absolute_error: 2185.2516
Epoch 97/100
323362/323362 [==============================] - 5s 15us/step - loss: 2190.7057 - mean_absolute_error: 2190.7057
Epoch 98/100
323362/323362 [==============================] - 4s 13us/step - loss: 2180.4480 - mean_absolute_error: 2180.4480
Epoch 99/100
323362/323362 [==============================] - 5s 14us/step - loss: 2184.2310 - mean_absolute_error: 2184.2310
Epoch 100/100
323362/323362 [==============================] - 4s 13us/step - loss: 2177.0971 - mean_absolute_error: 2177.0971
Epoch 1/100
359291/359291 [==============================] - 9s 24us/step - loss: 3909.4116 - mean_absolute_error: 3909.4116
Epoch 2/100
359291/359291 [==============================] - 5s 15us/step - loss: 3405.5610 - mean_absolute_error: 3405.5610
Epoch 3/100
359291/359291 [==============================] - 6s 16us/step - loss: 3092.9009 - mean_absolute_error: 3092.9009
Epoch 4/100
359291/359291 [==============================] - 4s 12us/step - loss: 2897.4427 - mean_absolute_error: 2897.4427
Epoch 5/100
359291/359291 [==============================] - 6s 16us/step - loss: 2798.5212 - mean_absolute_error: 2798.5212
Epoch 6/100
359291/359291 [==============================] - 6s 16us/step - loss: 2737.6311 - mean_absolute_error: 2737.6311
Epoch 7/100
359291/359291 [==============================] - 7s 20us/step - loss: 2693.2206 - mean_absolute_error: 2693.2206
Epoch 8/100
359291/359291 [==============================] - 5s 14us/step - loss: 2645.6897 - mean_absolute_error: 2645.6897
Epoch 9/100
359291/359291 [==============================] - 5s 15us/step - loss: 2620.4723 - mean_absolute_error: 2620.4723
Epoch 10/100
359291/359291 [==============================] - 5s 14us/step - loss: 2579.7500 - mean_absolute_error: 2579.7500
Epoch 11/100
359291/359291 [==============================] - 6s 16us/step - loss: 2546.0735 - mean_absolute_error: 2546.0735
Epoch 12/100
359291/359291 [==============================] - 5s 14us/step - loss: 2513.1809 - mean_absolute_error: 2513.1809
Epoch 13/100
359291/359291 [==============================] - 5s 14us/step - loss: 2494.3836 - mean_absolute_error: 2494.3836
Epoch 14/100
359291/359291 [==============================] - 5s 14us/step - loss: 2484.6616 - mean_absolute_error: 2484.6616
Epoch 15/100
359291/359291 [==============================] - 6s 16us/step - loss: 2461.7293 - mean_absolute_error: 2461.7293
Epoch 16/100
359291/359291 [==============================] - 5s 13us/step - loss: 2452.4036 - mean_absolute_error: 2452.4036
Epoch 17/100
359291/359291 [==============================] - 5s 15us/step - loss: 2446.1103 - mean_absolute_error: 2446.1103
Epoch 18/100
359291/359291 [==============================] - 5s 15us/step - loss: 2445.0293 - mean_absolute_error: 2445.0293
Epoch 19/100
359291/359291 [==============================] - 5s 14us/step - loss: 2438.6936 - mean_absolute_error: 2438.6936
Epoch 20/100
359291/359291 [==============================] - 5s 14us/step - loss: 2422.9926 - mean_absolute_error: 2422.9926
Epoch 21/100
359291/359291 [==============================] - 6s 18us/step - loss: 2419.3415 - mean_absolute_error: 2419.3415
Epoch 22/100
359291/359291 [==============================] - 5s 13us/step - loss: 2431.6264 - mean_absolute_error: 2431.6264
Epoch 23/100
359291/359291 [==============================] - 5s 13us/step - loss: 2404.8068 - mean_absolute_error: 2404.8068
Epoch 24/100
359291/359291 [==============================] - 5s 15us/step - loss: 2424.7358 - mean_absolute_error: 2424.7358
Epoch 25/100
359291/359291 [==============================] - 5s 13us/step - loss: 2395.0715 - mean_absolute_error: 2395.0715
Epoch 26/100
359291/359291 [==============================] - 5s 15us/step - loss: 2380.2846 - mean_absolute_error: 2380.2846
Epoch 27/100
359291/359291 [==============================] - 5s 13us/step - loss: 2383.3799 - mean_absolute_error: 2383.3799
Epoch 28/100
359291/359291 [==============================] - 5s 15us/step - loss: 2383.3764 - mean_absolute_error: 2383.3764
Epoch 29/100
359291/359291 [==============================] - 5s 13us/step - loss: 2369.7312 - mean_absolute_error: 2369.7312
Epoch 30/100
359291/359291 [==============================] - 6s 16us/step - loss: 2370.1079 - mean_absolute_error: 2370.1079
Epoch 31/100
359291/359291 [==============================] - 5s 13us/step - loss: 2377.0475 - mean_absolute_error: 2377.0475
Epoch 32/100
359291/359291 [==============================] - 6s 16us/step - loss: 2353.6415 - mean_absolute_error: 2353.6415
Epoch 33/100
359291/359291 [==============================] - 6s 17us/step - loss: 2354.0542 - mean_absolute_error: 2354.0542
Epoch 34/100
359291/359291 [==============================] - 7s 19us/step - loss: 2345.7112 - mean_absolute_error: 2345.7112
Epoch 35/100
359291/359291 [==============================] - 5s 13us/step - loss: 2336.4358 - mean_absolute_error: 2336.4358
Epoch 36/100
359291/359291 [==============================] - 5s 14us/step - loss: 2348.7270 - mean_absolute_error: 2348.7270
Epoch 37/100
359291/359291 [==============================] - 5s 13us/step - loss: 2334.4635 - mean_absolute_error: 2334.4635
Epoch 38/100
359291/359291 [==============================] - 6s 16us/step - loss: 2327.8598 - mean_absolute_error: 2327.8598
Epoch 39/100
359291/359291 [==============================] - 5s 14us/step - loss: 2334.5156 - mean_absolute_error: 2334.5156
Epoch 40/100
359291/359291 [==============================] - 6s 16us/step - loss: 2335.1257 - mean_absolute_error: 2335.1257
Epoch 41/100
359291/359291 [==============================] - 5s 15us/step - loss: 2335.2484 - mean_absolute_error: 2335.2484
Epoch 42/100
359291/359291 [==============================] - 6s 16us/step - loss: 2330.9733 - mean_absolute_error: 2330.9733
Epoch 43/100
359291/359291 [==============================] - 5s 14us/step - loss: 2341.1524 - mean_absolute_error: 2341.1524
Epoch 44/100
359291/359291 [==============================] - 6s 16us/step - loss: 2310.5233 - mean_absolute_error: 2310.5233
Epoch 45/100
359291/359291 [==============================] - 5s 14us/step - loss: 2314.6089 - mean_absolute_error: 2314.6089
Epoch 46/100
359291/359291 [==============================] - 6s 15us/step - loss: 2318.3160 - mean_absolute_error: 2318.3160
Epoch 47/100
359291/359291 [==============================] - 4s 12us/step - loss: 2317.3763 - mean_absolute_error: 2317.3763
Epoch 48/100
359291/359291 [==============================] - 6s 16us/step - loss: 2320.0046 - mean_absolute_error: 2320.0046
Epoch 49/100
359291/359291 [==============================] - 6s 16us/step - loss: 2309.2158 - mean_absolute_error: 2309.2158
Epoch 50/100
359291/359291 [==============================] - 6s 17us/step - loss: 2302.8712 - mean_absolute_error: 2302.8712
Epoch 51/100
359291/359291 [==============================] - 5s 14us/step - loss: 2312.4460 - mean_absolute_error: 2312.4460
Epoch 52/100
359291/359291 [==============================] - 5s 14us/step - loss: 2294.5484 - mean_absolute_error: 2294.5484
Epoch 53/100
359291/359291 [==============================] - 5s 15us/step - loss: 2300.3880 - mean_absolute_error: 2300.3880
Epoch 54/100
359291/359291 [==============================] - 5s 14us/step - loss: 2311.4724 - mean_absolute_error: 2311.4724
Epoch 55/100

359291/359291 [==============================] - 5s 14us/step - loss: 2290.9216 - mean_absolute_error: 2290.9216
Epoch 56/100
359291/359291 [==============================] - 5s 13us/step - loss: 2294.3468 - mean_absolute_error: 2294.3468
Epoch 57/100
359291/359291 [==============================] - 6s 16us/step - loss: 2297.2684 - mean_absolute_error: 2297.2684
Epoch 58/100
359291/359291 [==============================] - 4s 12us/step - loss: 2300.0216 - mean_absolute_error: 2300.0216
Epoch 59/100
359291/359291 [==============================] - 5s 14us/step - loss: 2292.6967 - mean_absolute_error: 2292.6967
Epoch 60/100
359291/359291 [==============================] - 4s 12us/step - loss: 2285.8953 - mean_absolute_error: 2285.8953
Epoch 61/100
359291/359291 [==============================] - 5s 14us/step - loss: 2285.0450 - mean_absolute_error: 2285.0450
Epoch 62/100
359291/359291 [==============================] - 5s 13us/step - loss: 2291.5283 - mean_absolute_error: 2291.5283
Epoch 63/100
359291/359291 [==============================] - 4s 12us/step - loss: 2282.0869 - mean_absolute_error: 2282.0869
Epoch 64/100
359291/359291 [==============================] - 6s 16us/step - loss: 2275.8443 - mean_absolute_error: 2275.8443
Epoch 65/100
359291/359291 [==============================] - 5s 13us/step - loss: 2279.7562 - mean_absolute_error: 2279.7562
Epoch 66/100
359291/359291 [==============================] - 4s 11us/step - loss: 2274.5853 - mean_absolute_error: 2274.5853
Epoch 67/100
359291/359291 [==============================] - 5s 15us/step - loss: 2264.7061 - mean_absolute_error: 2264.7061
Epoch 68/100
359291/359291 [==============================] - 7s 21us/step - loss: 2272.4404 - mean_absolute_error: 2272.4404
Epoch 69/100
359291/359291 [==============================] - 7s 18us/step - loss: 2273.3595 - mean_absolute_error: 2273.3595
Epoch 70/100
359291/359291 [==============================] - 6s 16us/step - loss: 2263.6464 - mean_absolute_error: 2263.6464
Epoch 71/100
359291/359291 [==============================] - 7s 19us/step - loss: 2270.7820 - mean_absolute_error: 2270.7820
Epoch 72/100
359291/359291 [==============================] - 9s 25us/step - loss: 2274.7457 - mean_absolute_error: 2274.7457
Epoch 73/100
359291/359291 [==============================] - 8s 22us/step - loss: 2262.9995 - mean_absolute_error: 2262.9995
Epoch 74/100
359291/359291 [==============================] - 8s 22us/step - loss: 2276.7622 - mean_absolute_error: 2276.7622
Epoch 75/100
359291/359291 [==============================] - 10s 27us/step - loss: 2258.8304 - mean_absolute_error: 2258.8304
Epoch 76/100
186900/359291 [==============>...............] - ETA: 5s - loss: 2257.0729 - mean_absolute_error: 2257.0729

KeyboardInterrupt: